/* This file was generated by casemap.py. */
/* Derived from Unicode data files, Unicode version ???. */
/* This does not get compiled into a cgunigen.o file; it's
 * #included in cgunicod.c. */

static gli_case_block_t unigen_case_block_0x0[256] = {
    { 0x0, 0x0 },
    { 0x1, 0x1 },
    { 0x2, 0x2 },
    { 0x3, 0x3 },
    { 0x4, 0x4 },
    { 0x5, 0x5 },
    { 0x6, 0x6 },
    { 0x7, 0x7 },
    { 0x8, 0x8 },
    { 0x9, 0x9 },
    { 0xa, 0xa },
    { 0xb, 0xb },
    { 0xc, 0xc },
    { 0xd, 0xd },
    { 0xe, 0xe },
    { 0xf, 0xf },
    { 0x10, 0x10 },
    { 0x11, 0x11 },
    { 0x12, 0x12 },
    { 0x13, 0x13 },
    { 0x14, 0x14 },
    { 0x15, 0x15 },
    { 0x16, 0x16 },
    { 0x17, 0x17 },
    { 0x18, 0x18 },
    { 0x19, 0x19 },
    { 0x1a, 0x1a },
    { 0x1b, 0x1b },
    { 0x1c, 0x1c },
    { 0x1d, 0x1d },
    { 0x1e, 0x1e },
    { 0x1f, 0x1f },
    { 0x20, 0x20 },
    { 0x21, 0x21 },
    { 0x22, 0x22 },
    { 0x23, 0x23 },
    { 0x24, 0x24 },
    { 0x25, 0x25 },
    { 0x26, 0x26 },
    { 0x27, 0x27 },
    { 0x28, 0x28 },
    { 0x29, 0x29 },
    { 0x2a, 0x2a },
    { 0x2b, 0x2b },
    { 0x2c, 0x2c },
    { 0x2d, 0x2d },
    { 0x2e, 0x2e },
    { 0x2f, 0x2f },
    { 0x30, 0x30 },
    { 0x31, 0x31 },
    { 0x32, 0x32 },
    { 0x33, 0x33 },
    { 0x34, 0x34 },
    { 0x35, 0x35 },
    { 0x36, 0x36 },
    { 0x37, 0x37 },
    { 0x38, 0x38 },
    { 0x39, 0x39 },
    { 0x3a, 0x3a },
    { 0x3b, 0x3b },
    { 0x3c, 0x3c },
    { 0x3d, 0x3d },
    { 0x3e, 0x3e },
    { 0x3f, 0x3f },
    { 0x40, 0x40 },
    { 0x41, 0x61 },  /* upper */
    { 0x42, 0x62 },  /* upper */
    { 0x43, 0x63 },  /* upper */
    { 0x44, 0x64 },  /* upper */
    { 0x45, 0x65 },  /* upper */
    { 0x46, 0x66 },  /* upper */
    { 0x47, 0x67 },  /* upper */
    { 0x48, 0x68 },  /* upper */
    { 0x49, 0x69 },  /* upper */
    { 0x4a, 0x6a },  /* upper */
    { 0x4b, 0x6b },  /* upper */
    { 0x4c, 0x6c },  /* upper */
    { 0x4d, 0x6d },  /* upper */
    { 0x4e, 0x6e },  /* upper */
    { 0x4f, 0x6f },  /* upper */
    { 0x50, 0x70 },  /* upper */
    { 0x51, 0x71 },  /* upper */
    { 0x52, 0x72 },  /* upper */
    { 0x53, 0x73 },  /* upper */
    { 0x54, 0x74 },  /* upper */
    { 0x55, 0x75 },  /* upper */
    { 0x56, 0x76 },  /* upper */
    { 0x57, 0x77 },  /* upper */
    { 0x58, 0x78 },  /* upper */
    { 0x59, 0x79 },  /* upper */
    { 0x5a, 0x7a },  /* upper */
    { 0x5b, 0x5b },
    { 0x5c, 0x5c },
    { 0x5d, 0x5d },
    { 0x5e, 0x5e },
    { 0x5f, 0x5f },
    { 0x60, 0x60 },
    { 0x41, 0x61 },  /* lower */
    { 0x42, 0x62 },  /* lower */
    { 0x43, 0x63 },  /* lower */
    { 0x44, 0x64 },  /* lower */
    { 0x45, 0x65 },  /* lower */
    { 0x46, 0x66 },  /* lower */
    { 0x47, 0x67 },  /* lower */
    { 0x48, 0x68 },  /* lower */
    { 0x49, 0x69 },  /* lower */
    { 0x4a, 0x6a },  /* lower */
    { 0x4b, 0x6b },  /* lower */
    { 0x4c, 0x6c },  /* lower */
    { 0x4d, 0x6d },  /* lower */
    { 0x4e, 0x6e },  /* lower */
    { 0x4f, 0x6f },  /* lower */
    { 0x50, 0x70 },  /* lower */
    { 0x51, 0x71 },  /* lower */
    { 0x52, 0x72 },  /* lower */
    { 0x53, 0x73 },  /* lower */
    { 0x54, 0x74 },  /* lower */
    { 0x55, 0x75 },  /* lower */
    { 0x56, 0x76 },  /* lower */
    { 0x57, 0x77 },  /* lower */
    { 0x58, 0x78 },  /* lower */
    { 0x59, 0x79 },  /* lower */
    { 0x5a, 0x7a },  /* lower */
    { 0x7b, 0x7b },
    { 0x7c, 0x7c },
    { 0x7d, 0x7d },
    { 0x7e, 0x7e },
    { 0x7f, 0x7f },
    { 0x80, 0x80 },
    { 0x81, 0x81 },
    { 0x82, 0x82 },
    { 0x83, 0x83 },
    { 0x84, 0x84 },
    { 0x85, 0x85 },
    { 0x86, 0x86 },
    { 0x87, 0x87 },
    { 0x88, 0x88 },
    { 0x89, 0x89 },
    { 0x8a, 0x8a },
    { 0x8b, 0x8b },
    { 0x8c, 0x8c },
    { 0x8d, 0x8d },
    { 0x8e, 0x8e },
    { 0x8f, 0x8f },
    { 0x90, 0x90 },
    { 0x91, 0x91 },
    { 0x92, 0x92 },
    { 0x93, 0x93 },
    { 0x94, 0x94 },
    { 0x95, 0x95 },
    { 0x96, 0x96 },
    { 0x97, 0x97 },
    { 0x98, 0x98 },
    { 0x99, 0x99 },
    { 0x9a, 0x9a },
    { 0x9b, 0x9b },
    { 0x9c, 0x9c },
    { 0x9d, 0x9d },
    { 0x9e, 0x9e },
    { 0x9f, 0x9f },
    { 0xa0, 0xa0 },
    { 0xa1, 0xa1 },
    { 0xa2, 0xa2 },
    { 0xa3, 0xa3 },
    { 0xa4, 0xa4 },
    { 0xa5, 0xa5 },
    { 0xa6, 0xa6 },
    { 0xa7, 0xa7 },
    { 0xa8, 0xa8 },
    { 0xa9, 0xa9 },
    { 0xaa, 0xaa },
    { 0xab, 0xab },
    { 0xac, 0xac },
    { 0xad, 0xad },
    { 0xae, 0xae },
    { 0xaf, 0xaf },
    { 0xb0, 0xb0 },
    { 0xb1, 0xb1 },
    { 0xb2, 0xb2 },
    { 0xb3, 0xb3 },
    { 0xb4, 0xb4 },
    { 0x39c, 0xb5 },  /* lower */
    { 0xb6, 0xb6 },
    { 0xb7, 0xb7 },
    { 0xb8, 0xb8 },
    { 0xb9, 0xb9 },
    { 0xba, 0xba },
    { 0xbb, 0xbb },
    { 0xbc, 0xbc },
    { 0xbd, 0xbd },
    { 0xbe, 0xbe },
    { 0xbf, 0xbf },
    { 0xc0, 0xe0 },  /* upper */
    { 0xc1, 0xe1 },  /* upper */
    { 0xc2, 0xe2 },  /* upper */
    { 0xc3, 0xe3 },  /* upper */
    { 0xc4, 0xe4 },  /* upper */
    { 0xc5, 0xe5 },  /* upper */
    { 0xc6, 0xe6 },  /* upper */
    { 0xc7, 0xe7 },  /* upper */
    { 0xc8, 0xe8 },  /* upper */
    { 0xc9, 0xe9 },  /* upper */
    { 0xca, 0xea },  /* upper */
    { 0xcb, 0xeb },  /* upper */
    { 0xcc, 0xec },  /* upper */
    { 0xcd, 0xed },  /* upper */
    { 0xce, 0xee },  /* upper */
    { 0xcf, 0xef },  /* upper */
    { 0xd0, 0xf0 },  /* upper */
    { 0xd1, 0xf1 },  /* upper */
    { 0xd2, 0xf2 },  /* upper */
    { 0xd3, 0xf3 },  /* upper */
    { 0xd4, 0xf4 },  /* upper */
    { 0xd5, 0xf5 },  /* upper */
    { 0xd6, 0xf6 },  /* upper */
    { 0xd7, 0xd7 },
    { 0xd8, 0xf8 },  /* upper */
    { 0xd9, 0xf9 },  /* upper */
    { 0xda, 0xfa },  /* upper */
    { 0xdb, 0xfb },  /* upper */
    { 0xdc, 0xfc },  /* upper */
    { 0xdd, 0xfd },  /* upper */
    { 0xde, 0xfe },  /* upper */
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xc0, 0xe0 },  /* lower */
    { 0xc1, 0xe1 },  /* lower */
    { 0xc2, 0xe2 },  /* lower */
    { 0xc3, 0xe3 },  /* lower */
    { 0xc4, 0xe4 },  /* lower */
    { 0xc5, 0xe5 },  /* lower */
    { 0xc6, 0xe6 },  /* lower */
    { 0xc7, 0xe7 },  /* lower */
    { 0xc8, 0xe8 },  /* lower */
    { 0xc9, 0xe9 },  /* lower */
    { 0xca, 0xea },  /* lower */
    { 0xcb, 0xeb },  /* lower */
    { 0xcc, 0xec },  /* lower */
    { 0xcd, 0xed },  /* lower */
    { 0xce, 0xee },  /* lower */
    { 0xcf, 0xef },  /* lower */
    { 0xd0, 0xf0 },  /* lower */
    { 0xd1, 0xf1 },  /* lower */
    { 0xd2, 0xf2 },  /* lower */
    { 0xd3, 0xf3 },  /* lower */
    { 0xd4, 0xf4 },  /* lower */
    { 0xd5, 0xf5 },  /* lower */
    { 0xd6, 0xf6 },  /* lower */
    { 0xf7, 0xf7 },
    { 0xd8, 0xf8 },  /* lower */
    { 0xd9, 0xf9 },  /* lower */
    { 0xda, 0xfa },  /* lower */
    { 0xdb, 0xfb },  /* lower */
    { 0xdc, 0xfc },  /* lower */
    { 0xdd, 0xfd },  /* lower */
    { 0xde, 0xfe },  /* lower */
    { 0x178, 0xff },  /* lower */
};

static gli_case_block_t unigen_case_block_0x1[256] = {
    { 0x100, 0x101 },  /* upper */
    { 0x100, 0x101 },  /* lower */
    { 0x102, 0x103 },  /* upper */
    { 0x102, 0x103 },  /* lower */
    { 0x104, 0x105 },  /* upper */
    { 0x104, 0x105 },  /* lower */
    { 0x106, 0x107 },  /* upper */
    { 0x106, 0x107 },  /* lower */
    { 0x108, 0x109 },  /* upper */
    { 0x108, 0x109 },  /* lower */
    { 0x10a, 0x10b },  /* upper */
    { 0x10a, 0x10b },  /* lower */
    { 0x10c, 0x10d },  /* upper */
    { 0x10c, 0x10d },  /* lower */
    { 0x10e, 0x10f },  /* upper */
    { 0x10e, 0x10f },  /* lower */
    { 0x110, 0x111 },  /* upper */
    { 0x110, 0x111 },  /* lower */
    { 0x112, 0x113 },  /* upper */
    { 0x112, 0x113 },  /* lower */
    { 0x114, 0x115 },  /* upper */
    { 0x114, 0x115 },  /* lower */
    { 0x116, 0x117 },  /* upper */
    { 0x116, 0x117 },  /* lower */
    { 0x118, 0x119 },  /* upper */
    { 0x118, 0x119 },  /* lower */
    { 0x11a, 0x11b },  /* upper */
    { 0x11a, 0x11b },  /* lower */
    { 0x11c, 0x11d },  /* upper */
    { 0x11c, 0x11d },  /* lower */
    { 0x11e, 0x11f },  /* upper */
    { 0x11e, 0x11f },  /* lower */
    { 0x120, 0x121 },  /* upper */
    { 0x120, 0x121 },  /* lower */
    { 0x122, 0x123 },  /* upper */
    { 0x122, 0x123 },  /* lower */
    { 0x124, 0x125 },  /* upper */
    { 0x124, 0x125 },  /* lower */
    { 0x126, 0x127 },  /* upper */
    { 0x126, 0x127 },  /* lower */
    { 0x128, 0x129 },  /* upper */
    { 0x128, 0x129 },  /* lower */
    { 0x12a, 0x12b },  /* upper */
    { 0x12a, 0x12b },  /* lower */
    { 0x12c, 0x12d },  /* upper */
    { 0x12c, 0x12d },  /* lower */
    { 0x12e, 0x12f },  /* upper */
    { 0x12e, 0x12f },  /* lower */
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0x49, 0x131 },  /* lower */
    { 0x132, 0x133 },  /* upper */
    { 0x132, 0x133 },  /* lower */
    { 0x134, 0x135 },  /* upper */
    { 0x134, 0x135 },  /* lower */
    { 0x136, 0x137 },  /* upper */
    { 0x136, 0x137 },  /* lower */
    { 0x138, 0x138 },
    { 0x139, 0x13a },  /* upper */
    { 0x139, 0x13a },  /* lower */
    { 0x13b, 0x13c },  /* upper */
    { 0x13b, 0x13c },  /* lower */
    { 0x13d, 0x13e },  /* upper */
    { 0x13d, 0x13e },  /* lower */
    { 0x13f, 0x140 },  /* upper */
    { 0x13f, 0x140 },  /* lower */
    { 0x141, 0x142 },  /* upper */
    { 0x141, 0x142 },  /* lower */
    { 0x143, 0x144 },  /* upper */
    { 0x143, 0x144 },  /* lower */
    { 0x145, 0x146 },  /* upper */
    { 0x145, 0x146 },  /* lower */
    { 0x147, 0x148 },  /* upper */
    { 0x147, 0x148 },  /* lower */
    { 0x149, 0x149 },
    { 0x14a, 0x14b },  /* upper */
    { 0x14a, 0x14b },  /* lower */
    { 0x14c, 0x14d },  /* upper */
    { 0x14c, 0x14d },  /* lower */
    { 0x14e, 0x14f },  /* upper */
    { 0x14e, 0x14f },  /* lower */
    { 0x150, 0x151 },  /* upper */
    { 0x150, 0x151 },  /* lower */
    { 0x152, 0x153 },  /* upper */
    { 0x152, 0x153 },  /* lower */
    { 0x154, 0x155 },  /* upper */
    { 0x154, 0x155 },  /* lower */
    { 0x156, 0x157 },  /* upper */
    { 0x156, 0x157 },  /* lower */
    { 0x158, 0x159 },  /* upper */
    { 0x158, 0x159 },  /* lower */
    { 0x15a, 0x15b },  /* upper */
    { 0x15a, 0x15b },  /* lower */
    { 0x15c, 0x15d },  /* upper */
    { 0x15c, 0x15d },  /* lower */
    { 0x15e, 0x15f },  /* upper */
    { 0x15e, 0x15f },  /* lower */
    { 0x160, 0x161 },  /* upper */
    { 0x160, 0x161 },  /* lower */
    { 0x162, 0x163 },  /* upper */
    { 0x162, 0x163 },  /* lower */
    { 0x164, 0x165 },  /* upper */
    { 0x164, 0x165 },  /* lower */
    { 0x166, 0x167 },  /* upper */
    { 0x166, 0x167 },  /* lower */
    { 0x168, 0x169 },  /* upper */
    { 0x168, 0x169 },  /* lower */
    { 0x16a, 0x16b },  /* upper */
    { 0x16a, 0x16b },  /* lower */
    { 0x16c, 0x16d },  /* upper */
    { 0x16c, 0x16d },  /* lower */
    { 0x16e, 0x16f },  /* upper */
    { 0x16e, 0x16f },  /* lower */
    { 0x170, 0x171 },  /* upper */
    { 0x170, 0x171 },  /* lower */
    { 0x172, 0x173 },  /* upper */
    { 0x172, 0x173 },  /* lower */
    { 0x174, 0x175 },  /* upper */
    { 0x174, 0x175 },  /* lower */
    { 0x176, 0x177 },  /* upper */
    { 0x176, 0x177 },  /* lower */
    { 0x178, 0xff },  /* upper */
    { 0x179, 0x17a },  /* upper */
    { 0x179, 0x17a },  /* lower */
    { 0x17b, 0x17c },  /* upper */
    { 0x17b, 0x17c },  /* lower */
    { 0x17d, 0x17e },  /* upper */
    { 0x17d, 0x17e },  /* lower */
    { 0x53, 0x17f },  /* lower */
    { 0x243, 0x180 },  /* lower */
    { 0x181, 0x253 },  /* upper */
    { 0x182, 0x183 },  /* upper */
    { 0x182, 0x183 },  /* lower */
    { 0x184, 0x185 },  /* upper */
    { 0x184, 0x185 },  /* lower */
    { 0x186, 0x254 },  /* upper */
    { 0x187, 0x188 },  /* upper */
    { 0x187, 0x188 },  /* lower */
    { 0x189, 0x256 },  /* upper */
    { 0x18a, 0x257 },  /* upper */
    { 0x18b, 0x18c },  /* upper */
    { 0x18b, 0x18c },  /* lower */
    { 0x18d, 0x18d },
    { 0x18e, 0x1dd },  /* upper */
    { 0x18f, 0x259 },  /* upper */
    { 0x190, 0x25b },  /* upper */
    { 0x191, 0x192 },  /* upper */
    { 0x191, 0x192 },  /* lower */
    { 0x193, 0x260 },  /* upper */
    { 0x194, 0x263 },  /* upper */
    { 0x1f6, 0x195 },  /* lower */
    { 0x196, 0x269 },  /* upper */
    { 0x197, 0x268 },  /* upper */
    { 0x198, 0x199 },  /* upper */
    { 0x198, 0x199 },  /* lower */
    { 0x23d, 0x19a },  /* lower */
    { 0xa7dc, 0x19b },  /* lower */
    { 0x19c, 0x26f },  /* upper */
    { 0x19d, 0x272 },  /* upper */
    { 0x220, 0x19e },  /* lower */
    { 0x19f, 0x275 },  /* upper */
    { 0x1a0, 0x1a1 },  /* upper */
    { 0x1a0, 0x1a1 },  /* lower */
    { 0x1a2, 0x1a3 },  /* upper */
    { 0x1a2, 0x1a3 },  /* lower */
    { 0x1a4, 0x1a5 },  /* upper */
    { 0x1a4, 0x1a5 },  /* lower */
    { 0x1a6, 0x280 },  /* upper */
    { 0x1a7, 0x1a8 },  /* upper */
    { 0x1a7, 0x1a8 },  /* lower */
    { 0x1a9, 0x283 },  /* upper */
    { 0x1aa, 0x1aa },
    { 0x1ab, 0x1ab },
    { 0x1ac, 0x1ad },  /* upper */
    { 0x1ac, 0x1ad },  /* lower */
    { 0x1ae, 0x288 },  /* upper */
    { 0x1af, 0x1b0 },  /* upper */
    { 0x1af, 0x1b0 },  /* lower */
    { 0x1b1, 0x28a },  /* upper */
    { 0x1b2, 0x28b },  /* upper */
    { 0x1b3, 0x1b4 },  /* upper */
    { 0x1b3, 0x1b4 },  /* lower */
    { 0x1b5, 0x1b6 },  /* upper */
    { 0x1b5, 0x1b6 },  /* lower */
    { 0x1b7, 0x292 },  /* upper */
    { 0x1b8, 0x1b9 },  /* upper */
    { 0x1b8, 0x1b9 },  /* lower */
    { 0x1ba, 0x1ba },
    { 0x1bb, 0x1bb },
    { 0x1bc, 0x1bd },  /* upper */
    { 0x1bc, 0x1bd },  /* lower */
    { 0x1be, 0x1be },
    { 0x1f7, 0x1bf },  /* lower */
    { 0x1c0, 0x1c0 },
    { 0x1c1, 0x1c1 },
    { 0x1c2, 0x1c2 },
    { 0x1c3, 0x1c3 },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0x1cd, 0x1ce },  /* upper */
    { 0x1cd, 0x1ce },  /* lower */
    { 0x1cf, 0x1d0 },  /* upper */
    { 0x1cf, 0x1d0 },  /* lower */
    { 0x1d1, 0x1d2 },  /* upper */
    { 0x1d1, 0x1d2 },  /* lower */
    { 0x1d3, 0x1d4 },  /* upper */
    { 0x1d3, 0x1d4 },  /* lower */
    { 0x1d5, 0x1d6 },  /* upper */
    { 0x1d5, 0x1d6 },  /* lower */
    { 0x1d7, 0x1d8 },  /* upper */
    { 0x1d7, 0x1d8 },  /* lower */
    { 0x1d9, 0x1da },  /* upper */
    { 0x1d9, 0x1da },  /* lower */
    { 0x1db, 0x1dc },  /* upper */
    { 0x1db, 0x1dc },  /* lower */
    { 0x18e, 0x1dd },  /* lower */
    { 0x1de, 0x1df },  /* upper */
    { 0x1de, 0x1df },  /* lower */
    { 0x1e0, 0x1e1 },  /* upper */
    { 0x1e0, 0x1e1 },  /* lower */
    { 0x1e2, 0x1e3 },  /* upper */
    { 0x1e2, 0x1e3 },  /* lower */
    { 0x1e4, 0x1e5 },  /* upper */
    { 0x1e4, 0x1e5 },  /* lower */
    { 0x1e6, 0x1e7 },  /* upper */
    { 0x1e6, 0x1e7 },  /* lower */
    { 0x1e8, 0x1e9 },  /* upper */
    { 0x1e8, 0x1e9 },  /* lower */
    { 0x1ea, 0x1eb },  /* upper */
    { 0x1ea, 0x1eb },  /* lower */
    { 0x1ec, 0x1ed },  /* upper */
    { 0x1ec, 0x1ed },  /* lower */
    { 0x1ee, 0x1ef },  /* upper */
    { 0x1ee, 0x1ef },  /* lower */
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0x1f4, 0x1f5 },  /* upper */
    { 0x1f4, 0x1f5 },  /* lower */
    { 0x1f6, 0x195 },  /* upper */
    { 0x1f7, 0x1bf },  /* upper */
    { 0x1f8, 0x1f9 },  /* upper */
    { 0x1f8, 0x1f9 },  /* lower */
    { 0x1fa, 0x1fb },  /* upper */
    { 0x1fa, 0x1fb },  /* lower */
    { 0x1fc, 0x1fd },  /* upper */
    { 0x1fc, 0x1fd },  /* lower */
    { 0x1fe, 0x1ff },  /* upper */
    { 0x1fe, 0x1ff },  /* lower */
};

static gli_case_block_t unigen_case_block_0x2[256] = {
    { 0x200, 0x201 },  /* upper */
    { 0x200, 0x201 },  /* lower */
    { 0x202, 0x203 },  /* upper */
    { 0x202, 0x203 },  /* lower */
    { 0x204, 0x205 },  /* upper */
    { 0x204, 0x205 },  /* lower */
    { 0x206, 0x207 },  /* upper */
    { 0x206, 0x207 },  /* lower */
    { 0x208, 0x209 },  /* upper */
    { 0x208, 0x209 },  /* lower */
    { 0x20a, 0x20b },  /* upper */
    { 0x20a, 0x20b },  /* lower */
    { 0x20c, 0x20d },  /* upper */
    { 0x20c, 0x20d },  /* lower */
    { 0x20e, 0x20f },  /* upper */
    { 0x20e, 0x20f },  /* lower */
    { 0x210, 0x211 },  /* upper */
    { 0x210, 0x211 },  /* lower */
    { 0x212, 0x213 },  /* upper */
    { 0x212, 0x213 },  /* lower */
    { 0x214, 0x215 },  /* upper */
    { 0x214, 0x215 },  /* lower */
    { 0x216, 0x217 },  /* upper */
    { 0x216, 0x217 },  /* lower */
    { 0x218, 0x219 },  /* upper */
    { 0x218, 0x219 },  /* lower */
    { 0x21a, 0x21b },  /* upper */
    { 0x21a, 0x21b },  /* lower */
    { 0x21c, 0x21d },  /* upper */
    { 0x21c, 0x21d },  /* lower */
    { 0x21e, 0x21f },  /* upper */
    { 0x21e, 0x21f },  /* lower */
    { 0x220, 0x19e },  /* upper */
    { 0x221, 0x221 },
    { 0x222, 0x223 },  /* upper */
    { 0x222, 0x223 },  /* lower */
    { 0x224, 0x225 },  /* upper */
    { 0x224, 0x225 },  /* lower */
    { 0x226, 0x227 },  /* upper */
    { 0x226, 0x227 },  /* lower */
    { 0x228, 0x229 },  /* upper */
    { 0x228, 0x229 },  /* lower */
    { 0x22a, 0x22b },  /* upper */
    { 0x22a, 0x22b },  /* lower */
    { 0x22c, 0x22d },  /* upper */
    { 0x22c, 0x22d },  /* lower */
    { 0x22e, 0x22f },  /* upper */
    { 0x22e, 0x22f },  /* lower */
    { 0x230, 0x231 },  /* upper */
    { 0x230, 0x231 },  /* lower */
    { 0x232, 0x233 },  /* upper */
    { 0x232, 0x233 },  /* lower */
    { 0x234, 0x234 },
    { 0x235, 0x235 },
    { 0x236, 0x236 },
    { 0x237, 0x237 },
    { 0x238, 0x238 },
    { 0x239, 0x239 },
    { 0x23a, 0x2c65 },  /* upper */
    { 0x23b, 0x23c },  /* upper */
    { 0x23b, 0x23c },  /* lower */
    { 0x23d, 0x19a },  /* upper */
    { 0x23e, 0x2c66 },  /* upper */
    { 0x2c7e, 0x23f },  /* lower */
    { 0x2c7f, 0x240 },  /* lower */
    { 0x241, 0x242 },  /* upper */
    { 0x241, 0x242 },  /* lower */
    { 0x243, 0x180 },  /* upper */
    { 0x244, 0x289 },  /* upper */
    { 0x245, 0x28c },  /* upper */
    { 0x246, 0x247 },  /* upper */
    { 0x246, 0x247 },  /* lower */
    { 0x248, 0x249 },  /* upper */
    { 0x248, 0x249 },  /* lower */
    { 0x24a, 0x24b },  /* upper */
    { 0x24a, 0x24b },  /* lower */
    { 0x24c, 0x24d },  /* upper */
    { 0x24c, 0x24d },  /* lower */
    { 0x24e, 0x24f },  /* upper */
    { 0x24e, 0x24f },  /* lower */
    { 0x250, 0x250 },
    { 0x251, 0x251 },
    { 0x252, 0x252 },
    { 0x253, 0x253 },
    { 0x254, 0x254 },
    { 0x255, 0x255 },
    { 0x256, 0x256 },
    { 0x257, 0x257 },
    { 0x258, 0x258 },
    { 0x259, 0x259 },
    { 0x25a, 0x25a },
    { 0x25b, 0x25b },
    { 0x25c, 0x25c },
    { 0x25d, 0x25d },
    { 0x25e, 0x25e },
    { 0x25f, 0x25f },
    { 0x260, 0x260 },
    { 0x261, 0x261 },
    { 0x262, 0x262 },
    { 0x263, 0x263 },
    { 0x264, 0x264 },
    { 0x265, 0x265 },
    { 0x266, 0x266 },
    { 0x267, 0x267 },
    { 0x268, 0x268 },
    { 0x269, 0x269 },
    { 0x26a, 0x26a },
    { 0x26b, 0x26b },
    { 0x26c, 0x26c },
    { 0x26d, 0x26d },
    { 0x26e, 0x26e },
    { 0x26f, 0x26f },
    { 0x270, 0x270 },
    { 0x271, 0x271 },
    { 0x272, 0x272 },
    { 0x273, 0x273 },
    { 0x274, 0x274 },
    { 0x275, 0x275 },
    { 0x276, 0x276 },
    { 0x277, 0x277 },
    { 0x278, 0x278 },
    { 0x279, 0x279 },
    { 0x27a, 0x27a },
    { 0x27b, 0x27b },
    { 0x27c, 0x27c },
    { 0x27d, 0x27d },
    { 0x27e, 0x27e },
    { 0x27f, 0x27f },
    { 0x280, 0x280 },
    { 0x281, 0x281 },
    { 0x282, 0x282 },
    { 0x283, 0x283 },
    { 0x284, 0x284 },
    { 0x285, 0x285 },
    { 0x286, 0x286 },
    { 0x287, 0x287 },
    { 0x288, 0x288 },
    { 0x289, 0x289 },
    { 0x28a, 0x28a },
    { 0x28b, 0x28b },
    { 0x28c, 0x28c },
    { 0x28d, 0x28d },
    { 0x28e, 0x28e },
    { 0x28f, 0x28f },
    { 0x290, 0x290 },
    { 0x291, 0x291 },
    { 0x292, 0x292 },
    { 0x293, 0x293 },
    { 0x294, 0x294 },
    { 0x295, 0x295 },
    { 0x296, 0x296 },
    { 0x297, 0x297 },
    { 0x298, 0x298 },
    { 0x299, 0x299 },
    { 0x29a, 0x29a },
    { 0x29b, 0x29b },
    { 0x29c, 0x29c },
    { 0x29d, 0x29d },
    { 0x29e, 0x29e },
    { 0x29f, 0x29f },
    { 0x2a0, 0x2a0 },
    { 0x2a1, 0x2a1 },
    { 0x2a2, 0x2a2 },
    { 0x2a3, 0x2a3 },
    { 0x2a4, 0x2a4 },
    { 0x2a5, 0x2a5 },
    { 0x2a6, 0x2a6 },
    { 0x2a7, 0x2a7 },
    { 0x2a8, 0x2a8 },
    { 0x2a9, 0x2a9 },
    { 0x2aa, 0x2aa },
    { 0x2ab, 0x2ab },
    { 0x2ac, 0x2ac },
    { 0x2ad, 0x2ad },
    { 0x2ae, 0x2ae },
    { 0x2af, 0x2af },
    { 0x2b0, 0x2b0 },
    { 0x2b1, 0x2b1 },
    { 0x2b2, 0x2b2 },
    { 0x2b3, 0x2b3 },
    { 0x2b4, 0x2b4 },
    { 0x2b5, 0x2b5 },
    { 0x2b6, 0x2b6 },
    { 0x2b7, 0x2b7 },
    { 0x2b8, 0x2b8 },
    { 0x2b9, 0x2b9 },
    { 0x2ba, 0x2ba },
    { 0x2bb, 0x2bb },
    { 0x2bc, 0x2bc },
    { 0x2bd, 0x2bd },
    { 0x2be, 0x2be },
    { 0x2bf, 0x2bf },
    { 0x2c0, 0x2c0 },
    { 0x2c1, 0x2c1 },
    { 0x2c2, 0x2c2 },
    { 0x2c3, 0x2c3 },
    { 0x2c4, 0x2c4 },
    { 0x2c5, 0x2c5 },
    { 0x2c6, 0x2c6 },
    { 0x2c7, 0x2c7 },
    { 0x2c8, 0x2c8 },
    { 0x2c9, 0x2c9 },
    { 0x2ca, 0x2ca },
    { 0x2cb, 0x2cb },
    { 0x2cc, 0x2cc },
    { 0x2cd, 0x2cd },
    { 0x2ce, 0x2ce },
    { 0x2cf, 0x2cf },
    { 0x2d0, 0x2d0 },
    { 0x2d1, 0x2d1 },
    { 0x2d2, 0x2d2 },
    { 0x2d3, 0x2d3 },
    { 0x2d4, 0x2d4 },
    { 0x2d5, 0x2d5 },
    { 0x2d6, 0x2d6 },
    { 0x2d7, 0x2d7 },
    { 0x2d8, 0x2d8 },
    { 0x2d9, 0x2d9 },
    { 0x2da, 0x2da },
    { 0x2db, 0x2db },
    { 0x2dc, 0x2dc },
    { 0x2dd, 0x2dd },
    { 0x2de, 0x2de },
    { 0x2df, 0x2df },
    { 0x2e0, 0x2e0 },
    { 0x2e1, 0x2e1 },
    { 0x2e2, 0x2e2 },
    { 0x2e3, 0x2e3 },
    { 0x2e4, 0x2e4 },
    { 0x2e5, 0x2e5 },
    { 0x2e6, 0x2e6 },
    { 0x2e7, 0x2e7 },
    { 0x2e8, 0x2e8 },
    { 0x2e9, 0x2e9 },
    { 0x2ea, 0x2ea },
    { 0x2eb, 0x2eb },
    { 0x2ec, 0x2ec },
    { 0x2ed, 0x2ed },
    { 0x2ee, 0x2ee },
    { 0x2ef, 0x2ef },
    { 0x2f0, 0x2f0 },
    { 0x2f1, 0x2f1 },
    { 0x2f2, 0x2f2 },
    { 0x2f3, 0x2f3 },
    { 0x2f4, 0x2f4 },
    { 0x2f5, 0x2f5 },
    { 0x2f6, 0x2f6 },
    { 0x2f7, 0x2f7 },
    { 0x2f8, 0x2f8 },
    { 0x2f9, 0x2f9 },
    { 0x2fa, 0x2fa },
    { 0x2fb, 0x2fb },
    { 0x2fc, 0x2fc },
    { 0x2fd, 0x2fd },
    { 0x2fe, 0x2fe },
    { 0x2ff, 0x2ff },
};

static gli_case_block_t unigen_case_block_0x3[256] = {
    { 0x300, 0x300 },
    { 0x301, 0x301 },
    { 0x302, 0x302 },
    { 0x303, 0x303 },
    { 0x304, 0x304 },
    { 0x305, 0x305 },
    { 0x306, 0x306 },
    { 0x307, 0x307 },
    { 0x308, 0x308 },
    { 0x309, 0x309 },
    { 0x30a, 0x30a },
    { 0x30b, 0x30b },
    { 0x30c, 0x30c },
    { 0x30d, 0x30d },
    { 0x30e, 0x30e },
    { 0x30f, 0x30f },
    { 0x310, 0x310 },
    { 0x311, 0x311 },
    { 0x312, 0x312 },
    { 0x313, 0x313 },
    { 0x314, 0x314 },
    { 0x315, 0x315 },
    { 0x316, 0x316 },
    { 0x317, 0x317 },
    { 0x318, 0x318 },
    { 0x319, 0x319 },
    { 0x31a, 0x31a },
    { 0x31b, 0x31b },
    { 0x31c, 0x31c },
    { 0x31d, 0x31d },
    { 0x31e, 0x31e },
    { 0x31f, 0x31f },
    { 0x320, 0x320 },
    { 0x321, 0x321 },
    { 0x322, 0x322 },
    { 0x323, 0x323 },
    { 0x324, 0x324 },
    { 0x325, 0x325 },
    { 0x326, 0x326 },
    { 0x327, 0x327 },
    { 0x328, 0x328 },
    { 0x329, 0x329 },
    { 0x32a, 0x32a },
    { 0x32b, 0x32b },
    { 0x32c, 0x32c },
    { 0x32d, 0x32d },
    { 0x32e, 0x32e },
    { 0x32f, 0x32f },
    { 0x330, 0x330 },
    { 0x331, 0x331 },
    { 0x332, 0x332 },
    { 0x333, 0x333 },
    { 0x334, 0x334 },
    { 0x335, 0x335 },
    { 0x336, 0x336 },
    { 0x337, 0x337 },
    { 0x338, 0x338 },
    { 0x339, 0x339 },
    { 0x33a, 0x33a },
    { 0x33b, 0x33b },
    { 0x33c, 0x33c },
    { 0x33d, 0x33d },
    { 0x33e, 0x33e },
    { 0x33f, 0x33f },
    { 0x340, 0x340 },
    { 0x341, 0x341 },
    { 0x342, 0x342 },
    { 0x343, 0x343 },
    { 0x344, 0x344 },
    { 0x399, 0x345 },  /* lower */
    { 0x346, 0x346 },
    { 0x347, 0x347 },
    { 0x348, 0x348 },
    { 0x349, 0x349 },
    { 0x34a, 0x34a },
    { 0x34b, 0x34b },
    { 0x34c, 0x34c },
    { 0x34d, 0x34d },
    { 0x34e, 0x34e },
    { 0x34f, 0x34f },
    { 0x350, 0x350 },
    { 0x351, 0x351 },
    { 0x352, 0x352 },
    { 0x353, 0x353 },
    { 0x354, 0x354 },
    { 0x355, 0x355 },
    { 0x356, 0x356 },
    { 0x357, 0x357 },
    { 0x358, 0x358 },
    { 0x359, 0x359 },
    { 0x35a, 0x35a },
    { 0x35b, 0x35b },
    { 0x35c, 0x35c },
    { 0x35d, 0x35d },
    { 0x35e, 0x35e },
    { 0x35f, 0x35f },
    { 0x360, 0x360 },
    { 0x361, 0x361 },
    { 0x362, 0x362 },
    { 0x363, 0x363 },
    { 0x364, 0x364 },
    { 0x365, 0x365 },
    { 0x366, 0x366 },
    { 0x367, 0x367 },
    { 0x368, 0x368 },
    { 0x369, 0x369 },
    { 0x36a, 0x36a },
    { 0x36b, 0x36b },
    { 0x36c, 0x36c },
    { 0x36d, 0x36d },
    { 0x36e, 0x36e },
    { 0x36f, 0x36f },
    { 0x370, 0x370 },
    { 0x371, 0x371 },
    { 0x372, 0x372 },
    { 0x373, 0x373 },
    { 0x374, 0x374 },
    { 0x375, 0x375 },
    { 0x376, 0x376 },
    { 0x377, 0x377 },
    { 0x378, 0x378 },
    { 0x379, 0x379 },
    { 0x37a, 0x37a },
    { 0x37b, 0x37b },
    { 0x37c, 0x37c },
    { 0x37d, 0x37d },
    { 0x37e, 0x37e },
    { 0x37f, 0x37f },
    { 0x380, 0x380 },
    { 0x381, 0x381 },
    { 0x382, 0x382 },
    { 0x383, 0x383 },
    { 0x384, 0x384 },
    { 0x385, 0x385 },
    { 0x386, 0x386 },
    { 0x387, 0x387 },
    { 0x388, 0x388 },
    { 0x389, 0x389 },
    { 0x38a, 0x38a },
    { 0x38b, 0x38b },
    { 0x38c, 0x38c },
    { 0x38d, 0x38d },
    { 0x38e, 0x38e },
    { 0x38f, 0x38f },
    { 0x390, 0x390 },
    { 0x391, 0x391 },
    { 0x392, 0x392 },
    { 0x393, 0x393 },
    { 0x394, 0x394 },
    { 0x395, 0x395 },
    { 0x396, 0x396 },
    { 0x397, 0x397 },
    { 0x398, 0x398 },
    { 0x399, 0x399 },
    { 0x39a, 0x39a },
    { 0x39b, 0x39b },
    { 0x39c, 0x39c },
    { 0x39d, 0x39d },
    { 0x39e, 0x39e },
    { 0x39f, 0x39f },
    { 0x3a0, 0x3a0 },
    { 0x3a1, 0x3a1 },
    { 0x3a2, 0x3a2 },
    { 0x3a3, 0x3a3 },
    { 0x3a4, 0x3a4 },
    { 0x3a5, 0x3a5 },
    { 0x3a6, 0x3a6 },
    { 0x3a7, 0x3a7 },
    { 0x3a8, 0x3a8 },
    { 0x3a9, 0x3a9 },
    { 0x3aa, 0x3aa },
    { 0x3ab, 0x3ab },
    { 0x3ac, 0x3ac },
    { 0x3ad, 0x3ad },
    { 0x3ae, 0x3ae },
    { 0x3af, 0x3af },
    { 0x3b0, 0x3b0 },
    { 0x3b1, 0x3b1 },
    { 0x3b2, 0x3b2 },
    { 0x3b3, 0x3b3 },
    { 0x3b4, 0x3b4 },
    { 0x3b5, 0x3b5 },
    { 0x3b6, 0x3b6 },
    { 0x3b7, 0x3b7 },
    { 0x3b8, 0x3b8 },
    { 0x3b9, 0x3b9 },
    { 0x3ba, 0x3ba },
    { 0x3bb, 0x3bb },
    { 0x3bc, 0x3bc },
    { 0x3bd, 0x3bd },
    { 0x3be, 0x3be },
    { 0x3bf, 0x3bf },
    { 0x3c0, 0x3c0 },
    { 0x3c1, 0x3c1 },
    { 0x3c2, 0x3c2 },
    { 0x3c3, 0x3c3 },
    { 0x3c4, 0x3c4 },
    { 0x3c5, 0x3c5 },
    { 0x3c6, 0x3c6 },
    { 0x3c7, 0x3c7 },
    { 0x3c8, 0x3c8 },
    { 0x3c9, 0x3c9 },
    { 0x3ca, 0x3ca },
    { 0x3cb, 0x3cb },
    { 0x3cc, 0x3cc },
    { 0x3cd, 0x3cd },
    { 0x3ce, 0x3ce },
    { 0x3cf, 0x3cf },
    { 0x3d0, 0x3d0 },
    { 0x3d1, 0x3d1 },
    { 0x3d2, 0x3d2 },
    { 0x3d3, 0x3d3 },
    { 0x3d4, 0x3d4 },
    { 0x3d5, 0x3d5 },
    { 0x3d6, 0x3d6 },
    { 0x3d7, 0x3d7 },
    { 0x3d8, 0x3d8 },
    { 0x3d9, 0x3d9 },
    { 0x3da, 0x3da },
    { 0x3db, 0x3db },
    { 0x3dc, 0x3dc },
    { 0x3dd, 0x3dd },
    { 0x3de, 0x3de },
    { 0x3df, 0x3df },
    { 0x3e0, 0x3e0 },
    { 0x3e1, 0x3e1 },
    { 0x3e2, 0x3e2 },
    { 0x3e3, 0x3e3 },
    { 0x3e4, 0x3e4 },
    { 0x3e5, 0x3e5 },
    { 0x3e6, 0x3e6 },
    { 0x3e7, 0x3e7 },
    { 0x3e8, 0x3e8 },
    { 0x3e9, 0x3e9 },
    { 0x3ea, 0x3ea },
    { 0x3eb, 0x3eb },
    { 0x3ec, 0x3ec },
    { 0x3ed, 0x3ed },
    { 0x3ee, 0x3ee },
    { 0x3ef, 0x3ef },
    { 0x3f0, 0x3f0 },
    { 0x3f1, 0x3f1 },
    { 0x3f2, 0x3f2 },
    { 0x3f3, 0x3f3 },
    { 0x3f4, 0x3f4 },
    { 0x3f5, 0x3f5 },
    { 0x3f6, 0x3f6 },
    { 0x3f7, 0x3f7 },
    { 0x3f8, 0x3f8 },
    { 0x3f9, 0x3f9 },
    { 0x3fa, 0x3fa },
    { 0x3fb, 0x3fb },
    { 0x3fc, 0x3fc },
    { 0x3fd, 0x3fd },
    { 0x3fe, 0x3fe },
    { 0x3ff, 0x3ff },
};

static gli_case_block_t unigen_case_block_0x1e[256] = {
    { 0x1e00, 0x1e01 },  /* upper */
    { 0x1e00, 0x1e01 },  /* lower */
    { 0x1e02, 0x1e03 },  /* upper */
    { 0x1e02, 0x1e03 },  /* lower */
    { 0x1e04, 0x1e05 },  /* upper */
    { 0x1e04, 0x1e05 },  /* lower */
    { 0x1e06, 0x1e07 },  /* upper */
    { 0x1e06, 0x1e07 },  /* lower */
    { 0x1e08, 0x1e09 },  /* upper */
    { 0x1e08, 0x1e09 },  /* lower */
    { 0x1e0a, 0x1e0b },  /* upper */
    { 0x1e0a, 0x1e0b },  /* lower */
    { 0x1e0c, 0x1e0d },  /* upper */
    { 0x1e0c, 0x1e0d },  /* lower */
    { 0x1e0e, 0x1e0f },  /* upper */
    { 0x1e0e, 0x1e0f },  /* lower */
    { 0x1e10, 0x1e11 },  /* upper */
    { 0x1e10, 0x1e11 },  /* lower */
    { 0x1e12, 0x1e13 },  /* upper */
    { 0x1e12, 0x1e13 },  /* lower */
    { 0x1e14, 0x1e15 },  /* upper */
    { 0x1e14, 0x1e15 },  /* lower */
    { 0x1e16, 0x1e17 },  /* upper */
    { 0x1e16, 0x1e17 },  /* lower */
    { 0x1e18, 0x1e19 },  /* upper */
    { 0x1e18, 0x1e19 },  /* lower */
    { 0x1e1a, 0x1e1b },  /* upper */
    { 0x1e1a, 0x1e1b },  /* lower */
    { 0x1e1c, 0x1e1d },  /* upper */
    { 0x1e1c, 0x1e1d },  /* lower */
    { 0x1e1e, 0x1e1f },  /* upper */
    { 0x1e1e, 0x1e1f },  /* lower */
    { 0x1e20, 0x1e21 },  /* upper */
    { 0x1e20, 0x1e21 },  /* lower */
    { 0x1e22, 0x1e23 },  /* upper */
    { 0x1e22, 0x1e23 },  /* lower */
    { 0x1e24, 0x1e25 },  /* upper */
    { 0x1e24, 0x1e25 },  /* lower */
    { 0x1e26, 0x1e27 },  /* upper */
    { 0x1e26, 0x1e27 },  /* lower */
    { 0x1e28, 0x1e29 },  /* upper */
    { 0x1e28, 0x1e29 },  /* lower */
    { 0x1e2a, 0x1e2b },  /* upper */
    { 0x1e2a, 0x1e2b },  /* lower */
    { 0x1e2c, 0x1e2d },  /* upper */
    { 0x1e2c, 0x1e2d },  /* lower */
    { 0x1e2e, 0x1e2f },  /* upper */
    { 0x1e2e, 0x1e2f },  /* lower */
    { 0x1e30, 0x1e31 },  /* upper */
    { 0x1e30, 0x1e31 },  /* lower */
    { 0x1e32, 0x1e33 },  /* upper */
    { 0x1e32, 0x1e33 },  /* lower */
    { 0x1e34, 0x1e35 },  /* upper */
    { 0x1e34, 0x1e35 },  /* lower */
    { 0x1e36, 0x1e37 },  /* upper */
    { 0x1e36, 0x1e37 },  /* lower */
    { 0x1e38, 0x1e39 },  /* upper */
    { 0x1e38, 0x1e39 },  /* lower */
    { 0x1e3a, 0x1e3b },  /* upper */
    { 0x1e3a, 0x1e3b },  /* lower */
    { 0x1e3c, 0x1e3d },  /* upper */
    { 0x1e3c, 0x1e3d },  /* lower */
    { 0x1e3e, 0x1e3f },  /* upper */
    { 0x1e3e, 0x1e3f },  /* lower */
    { 0x1e40, 0x1e41 },  /* upper */
    { 0x1e40, 0x1e41 },  /* lower */
    { 0x1e42, 0x1e43 },  /* upper */
    { 0x1e42, 0x1e43 },  /* lower */
    { 0x1e44, 0x1e45 },  /* upper */
    { 0x1e44, 0x1e45 },  /* lower */
    { 0x1e46, 0x1e47 },  /* upper */
    { 0x1e46, 0x1e47 },  /* lower */
    { 0x1e48, 0x1e49 },  /* upper */
    { 0x1e48, 0x1e49 },  /* lower */
    { 0x1e4a, 0x1e4b },  /* upper */
    { 0x1e4a, 0x1e4b },  /* lower */
    { 0x1e4c, 0x1e4d },  /* upper */
    { 0x1e4c, 0x1e4d },  /* lower */
    { 0x1e4e, 0x1e4f },  /* upper */
    { 0x1e4e, 0x1e4f },  /* lower */
    { 0x1e50, 0x1e51 },  /* upper */
    { 0x1e50, 0x1e51 },  /* lower */
    { 0x1e52, 0x1e53 },  /* upper */
    { 0x1e52, 0x1e53 },  /* lower */
    { 0x1e54, 0x1e55 },  /* upper */
    { 0x1e54, 0x1e55 },  /* lower */
    { 0x1e56, 0x1e57 },  /* upper */
    { 0x1e56, 0x1e57 },  /* lower */
    { 0x1e58, 0x1e59 },  /* upper */
    { 0x1e58, 0x1e59 },  /* lower */
    { 0x1e5a, 0x1e5b },  /* upper */
    { 0x1e5a, 0x1e5b },  /* lower */
    { 0x1e5c, 0x1e5d },  /* upper */
    { 0x1e5c, 0x1e5d },  /* lower */
    { 0x1e5e, 0x1e5f },  /* upper */
    { 0x1e5e, 0x1e5f },  /* lower */
    { 0x1e60, 0x1e61 },  /* upper */
    { 0x1e60, 0x1e61 },  /* lower */
    { 0x1e62, 0x1e63 },  /* upper */
    { 0x1e62, 0x1e63 },  /* lower */
    { 0x1e64, 0x1e65 },  /* upper */
    { 0x1e64, 0x1e65 },  /* lower */
    { 0x1e66, 0x1e67 },  /* upper */
    { 0x1e66, 0x1e67 },  /* lower */
    { 0x1e68, 0x1e69 },  /* upper */
    { 0x1e68, 0x1e69 },  /* lower */
    { 0x1e6a, 0x1e6b },  /* upper */
    { 0x1e6a, 0x1e6b },  /* lower */
    { 0x1e6c, 0x1e6d },  /* upper */
    { 0x1e6c, 0x1e6d },  /* lower */
    { 0x1e6e, 0x1e6f },  /* upper */
    { 0x1e6e, 0x1e6f },  /* lower */
    { 0x1e70, 0x1e71 },  /* upper */
    { 0x1e70, 0x1e71 },  /* lower */
    { 0x1e72, 0x1e73 },  /* upper */
    { 0x1e72, 0x1e73 },  /* lower */
    { 0x1e74, 0x1e75 },  /* upper */
    { 0x1e74, 0x1e75 },  /* lower */
    { 0x1e76, 0x1e77 },  /* upper */
    { 0x1e76, 0x1e77 },  /* lower */
    { 0x1e78, 0x1e79 },  /* upper */
    { 0x1e78, 0x1e79 },  /* lower */
    { 0x1e7a, 0x1e7b },  /* upper */
    { 0x1e7a, 0x1e7b },  /* lower */
    { 0x1e7c, 0x1e7d },  /* upper */
    { 0x1e7c, 0x1e7d },  /* lower */
    { 0x1e7e, 0x1e7f },  /* upper */
    { 0x1e7e, 0x1e7f },  /* lower */
    { 0x1e80, 0x1e81 },  /* upper */
    { 0x1e80, 0x1e81 },  /* lower */
    { 0x1e82, 0x1e83 },  /* upper */
    { 0x1e82, 0x1e83 },  /* lower */
    { 0x1e84, 0x1e85 },  /* upper */
    { 0x1e84, 0x1e85 },  /* lower */
    { 0x1e86, 0x1e87 },  /* upper */
    { 0x1e86, 0x1e87 },  /* lower */
    { 0x1e88, 0x1e89 },  /* upper */
    { 0x1e88, 0x1e89 },  /* lower */
    { 0x1e8a, 0x1e8b },  /* upper */
    { 0x1e8a, 0x1e8b },  /* lower */
    { 0x1e8c, 0x1e8d },  /* upper */
    { 0x1e8c, 0x1e8d },  /* lower */
    { 0x1e8e, 0x1e8f },  /* upper */
    { 0x1e8e, 0x1e8f },  /* lower */
    { 0x1e90, 0x1e91 },  /* upper */
    { 0x1e90, 0x1e91 },  /* lower */
    { 0x1e92, 0x1e93 },  /* upper */
    { 0x1e92, 0x1e93 },  /* lower */
    { 0x1e94, 0x1e95 },  /* upper */
    { 0x1e94, 0x1e95 },  /* lower */
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0xFFFFFFFF, 0xFFFFFFFF },
    { 0x1e9a, 0x1e9a },
    { 0x1e60, 0x1e9b },  /* lower */
    { 0x1e9c, 0x1e9c },
    { 0x1e9d, 0x1e9d },
    { 0x1e9e, 0xdf },  /* upper */
    { 0x1e9f, 0x1e9f },
    { 0x1ea0, 0x1ea1 },  /* upper */
    { 0x1ea0, 0x1ea1 },  /* lower */
    { 0x1ea2, 0x1ea3 },  /* upper */
    { 0x1ea2, 0x1ea3 },  /* lower */
    { 0x1ea4, 0x1ea5 },  /* upper */
    { 0x1ea4, 0x1ea5 },  /* lower */
    { 0x1ea6, 0x1ea7 },  /* upper */
    { 0x1ea6, 0x1ea7 },  /* lower */
    { 0x1ea8, 0x1ea9 },  /* upper */
    { 0x1ea8, 0x1ea9 },  /* lower */
    { 0x1eaa, 0x1eab },  /* upper */
    { 0x1eaa, 0x1eab },  /* lower */
    { 0x1eac, 0x1ead },  /* upper */
    { 0x1eac, 0x1ead },  /* lower */
    { 0x1eae, 0x1eaf },  /* upper */
    { 0x1eae, 0x1eaf },  /* lower */
    { 0x1eb0, 0x1eb1 },  /* upper */
    { 0x1eb0, 0x1eb1 },  /* lower */
    { 0x1eb2, 0x1eb3 },  /* upper */
    { 0x1eb2, 0x1eb3 },  /* lower */
    { 0x1eb4, 0x1eb5 },  /* upper */
    { 0x1eb4, 0x1eb5 },  /* lower */
    { 0x1eb6, 0x1eb7 },  /* upper */
    { 0x1eb6, 0x1eb7 },  /* lower */
    { 0x1eb8, 0x1eb9 },  /* upper */
    { 0x1eb8, 0x1eb9 },  /* lower */
    { 0x1eba, 0x1ebb },  /* upper */
    { 0x1eba, 0x1ebb },  /* lower */
    { 0x1ebc, 0x1ebd },  /* upper */
    { 0x1ebc, 0x1ebd },  /* lower */
    { 0x1ebe, 0x1ebf },  /* upper */
    { 0x1ebe, 0x1ebf },  /* lower */
    { 0x1ec0, 0x1ec1 },  /* upper */
    { 0x1ec0, 0x1ec1 },  /* lower */
    { 0x1ec2, 0x1ec3 },  /* upper */
    { 0x1ec2, 0x1ec3 },  /* lower */
    { 0x1ec4, 0x1ec5 },  /* upper */
    { 0x1ec4, 0x1ec5 },  /* lower */
    { 0x1ec6, 0x1ec7 },  /* upper */
    { 0x1ec6, 0x1ec7 },  /* lower */
    { 0x1ec8, 0x1ec9 },  /* upper */
    { 0x1ec8, 0x1ec9 },  /* lower */
    { 0x1eca, 0x1ecb },  /* upper */
    { 0x1eca, 0x1ecb },  /* lower */
    { 0x1ecc, 0x1ecd },  /* upper */
    { 0x1ecc, 0x1ecd },  /* lower */
    { 0x1ece, 0x1ecf },  /* upper */
    { 0x1ece, 0x1ecf },  /* lower */
    { 0x1ed0, 0x1ed1 },  /* upper */
    { 0x1ed0, 0x1ed1 },  /* lower */
    { 0x1ed2, 0x1ed3 },  /* upper */
    { 0x1ed2, 0x1ed3 },  /* lower */
    { 0x1ed4, 0x1ed5 },  /* upper */
    { 0x1ed4, 0x1ed5 },  /* lower */
    { 0x1ed6, 0x1ed7 },  /* upper */
    { 0x1ed6, 0x1ed7 },  /* lower */
    { 0x1ed8, 0x1ed9 },  /* upper */
    { 0x1ed8, 0x1ed9 },  /* lower */
    { 0x1eda, 0x1edb },  /* upper */
    { 0x1eda, 0x1edb },  /* lower */
    { 0x1edc, 0x1edd },  /* upper */
    { 0x1edc, 0x1edd },  /* lower */
    { 0x1ede, 0x1edf },  /* upper */
    { 0x1ede, 0x1edf },  /* lower */
    { 0x1ee0, 0x1ee1 },  /* upper */
    { 0x1ee0, 0x1ee1 },  /* lower */
    { 0x1ee2, 0x1ee3 },  /* upper */
    { 0x1ee2, 0x1ee3 },  /* lower */
    { 0x1ee4, 0x1ee5 },  /* upper */
    { 0x1ee4, 0x1ee5 },  /* lower */
    { 0x1ee6, 0x1ee7 },  /* upper */
    { 0x1ee6, 0x1ee7 },  /* lower */
    { 0x1ee8, 0x1ee9 },  /* upper */
    { 0x1ee8, 0x1ee9 },  /* lower */
    { 0x1eea, 0x1eeb },  /* upper */
    { 0x1eea, 0x1eeb },  /* lower */
    { 0x1eec, 0x1eed },  /* upper */
    { 0x1eec, 0x1eed },  /* lower */
    { 0x1eee, 0x1eef },  /* upper */
    { 0x1eee, 0x1eef },  /* lower */
    { 0x1ef0, 0x1ef1 },  /* upper */
    { 0x1ef0, 0x1ef1 },  /* lower */
    { 0x1ef2, 0x1ef3 },  /* upper */
    { 0x1ef2, 0x1ef3 },  /* lower */
    { 0x1ef4, 0x1ef5 },  /* upper */
    { 0x1ef4, 0x1ef5 },  /* lower */
    { 0x1ef6, 0x1ef7 },  /* upper */
    { 0x1ef6, 0x1ef7 },  /* lower */
    { 0x1ef8, 0x1ef9 },  /* upper */
    { 0x1ef8, 0x1ef9 },  /* lower */
    { 0x1efa, 0x1efb },  /* upper */
    { 0x1efa, 0x1efb },  /* lower */
    { 0x1efc, 0x1efd },  /* upper */
    { 0x1efc, 0x1efd },  /* lower */
    { 0x1efe, 0x1eff },  /* upper */
    { 0x1efe, 0x1eff },  /* lower */
};

#define GET_CASE_BLOCK(ch, blockptr)  \
switch ((glui32)(ch) >> 8) {  \
    case 0x0:  \
        *blockptr = unigen_case_block_0x0;  \
        break;  \
    case 0x1:  \
        *blockptr = unigen_case_block_0x1;  \
        break;  \
    case 0x2:  \
        *blockptr = unigen_case_block_0x2;  \
        break;  \
    case 0x3:  \
        *blockptr = unigen_case_block_0x3;  \
        break;  \
    case 0x1e:  \
        *blockptr = unigen_case_block_0x1e;  \
        break;  \
    default:  \
        *blockptr = NULL;  \
}
static glui32 unigen_special_array[] = {
    2, 0x53, 0x53,  /* 0xdf upcase */
    1, 0xdf,  /* 0xdf downcase */
    2, 0x53, 0x73,  /* 0xdf titlecase */
    1, 0x130,  /* 0x130 upcase */
    2, 0x69, 0x307,  /* 0x130 downcase */
    1, 0x130,  /* 0x130 titlecase */
    1, 0x1c4,  /* 0x1c4 upcase */
    1, 0x1c6,  /* 0x1c4 downcase */
    1, 0x1c5,  /* 0x1c4 titlecase */
    1, 0x1c4,  /* 0x1c5 upcase */
    1, 0x1c6,  /* 0x1c5 downcase */
    1, 0x1c5,  /* 0x1c5 titlecase */
    1, 0x1c4,  /* 0x1c6 upcase */
    1, 0x1c6,  /* 0x1c6 downcase */
    1, 0x1c5,  /* 0x1c6 titlecase */
    1, 0x1c7,  /* 0x1c7 upcase */
    1, 0x1c9,  /* 0x1c7 downcase */
    1, 0x1c8,  /* 0x1c7 titlecase */
    1, 0x1c7,  /* 0x1c8 upcase */
    1, 0x1c9,  /* 0x1c8 downcase */
    1, 0x1c8,  /* 0x1c8 titlecase */
    1, 0x1c7,  /* 0x1c9 upcase */
    1, 0x1c9,  /* 0x1c9 downcase */
    1, 0x1c8,  /* 0x1c9 titlecase */
    1, 0x1ca,  /* 0x1ca upcase */
    1, 0x1cc,  /* 0x1ca downcase */
    1, 0x1cb,  /* 0x1ca titlecase */
    1, 0x1ca,  /* 0x1cb upcase */
    1, 0x1cc,  /* 0x1cb downcase */
    1, 0x1cb,  /* 0x1cb titlecase */
    1, 0x1ca,  /* 0x1cc upcase */
    1, 0x1cc,  /* 0x1cc downcase */
    1, 0x1cb,  /* 0x1cc titlecase */
    2, 0x4a, 0x30c,  /* 0x1f0 upcase */
    1, 0x1f0,  /* 0x1f0 downcase */
    2, 0x4a, 0x30c,  /* 0x1f0 titlecase */
    1, 0x1f1,  /* 0x1f1 upcase */
    1, 0x1f3,  /* 0x1f1 downcase */
    1, 0x1f2,  /* 0x1f1 titlecase */
    1, 0x1f1,  /* 0x1f2 upcase */
    1, 0x1f3,  /* 0x1f2 downcase */
    1, 0x1f2,  /* 0x1f2 titlecase */
    1, 0x1f1,  /* 0x1f3 upcase */
    1, 0x1f3,  /* 0x1f3 downcase */
    1, 0x1f2,  /* 0x1f3 titlecase */
    2, 0x48, 0x331,  /* 0x1e96 upcase */
    1, 0x1e96,  /* 0x1e96 downcase */
    2, 0x48, 0x331,  /* 0x1e96 titlecase */
    2, 0x54, 0x308,  /* 0x1e97 upcase */
    1, 0x1e97,  /* 0x1e97 downcase */
    2, 0x54, 0x308,  /* 0x1e97 titlecase */
    2, 0x57, 0x30a,  /* 0x1e98 upcase */
    1, 0x1e98,  /* 0x1e98 downcase */
    2, 0x57, 0x30a,  /* 0x1e98 titlecase */
    2, 0x59, 0x30a,  /* 0x1e99 upcase */
    1, 0x1e99,  /* 0x1e99 downcase */
    2, 0x59, 0x30a,  /* 0x1e99 titlecase */
};

static gli_case_special_t unigen_special_0xdf = { 0, 3, 5 };
static gli_case_special_t unigen_special_0x130 = { 8, 10, 13 };
static gli_case_special_t unigen_special_0x1c4 = { 15, 17, 19 };
static gli_case_special_t unigen_special_0x1c5 = { 21, 23, 25 };
static gli_case_special_t unigen_special_0x1c6 = { 27, 29, 31 };
static gli_case_special_t unigen_special_0x1c7 = { 33, 35, 37 };
static gli_case_special_t unigen_special_0x1c8 = { 39, 41, 43 };
static gli_case_special_t unigen_special_0x1c9 = { 45, 47, 49 };
static gli_case_special_t unigen_special_0x1ca = { 51, 53, 55 };
static gli_case_special_t unigen_special_0x1cb = { 57, 59, 61 };
static gli_case_special_t unigen_special_0x1cc = { 63, 65, 67 };
static gli_case_special_t unigen_special_0x1f0 = { 69, 72, 74 };
static gli_case_special_t unigen_special_0x1f1 = { 77, 79, 81 };
static gli_case_special_t unigen_special_0x1f2 = { 83, 85, 87 };
static gli_case_special_t unigen_special_0x1f3 = { 89, 91, 93 };
static gli_case_special_t unigen_special_0x1e96 = { 95, 98, 100 };
static gli_case_special_t unigen_special_0x1e97 = { 103, 106, 108 };
static gli_case_special_t unigen_special_0x1e98 = { 111, 114, 116 };
static gli_case_special_t unigen_special_0x1e99 = { 119, 122, 124 };

#define GET_CASE_SPECIAL(ch, specptr)  \
switch (ch) {  \
    case 0xdf:  \
        *specptr = unigen_special_0xdf;  \
        break;  \
    case 0x130:  \
        *specptr = unigen_special_0x130;  \
        break;  \
    case 0x1c4:  \
        *specptr = unigen_special_0x1c4;  \
        break;  \
    case 0x1c5:  \
        *specptr = unigen_special_0x1c5;  \
        break;  \
    case 0x1c6:  \
        *specptr = unigen_special_0x1c6;  \
        break;  \
    case 0x1c7:  \
        *specptr = unigen_special_0x1c7;  \
        break;  \
    case 0x1c8:  \
        *specptr = unigen_special_0x1c8;  \
        break;  \
    case 0x1c9:  \
        *specptr = unigen_special_0x1c9;  \
        break;  \
    case 0x1ca:  \
        *specptr = unigen_special_0x1ca;  \
        break;  \
    case 0x1cb:  \
        *specptr = unigen_special_0x1cb;  \
        break;  \
    case 0x1cc:  \
        *specptr = unigen_special_0x1cc;  \
        break;  \
    case 0x1f0:  \
        *specptr = unigen_special_0x1f0;  \
        break;  \
    case 0x1f1:  \
        *specptr = unigen_special_0x1f1;  \
        break;  \
    case 0x1f2:  \
        *specptr = unigen_special_0x1f2;  \
        break;  \
    case 0x1f3:  \
        *specptr = unigen_special_0x1f3;  \
        break;  \
    case 0x1e96:  \
        *specptr = unigen_special_0x1e96;  \
        break;  \
    case 0x1e97:  \
        *specptr = unigen_special_0x1e97;  \
        break;  \
    case 0x1e98:  \
        *specptr = unigen_special_0x1e98;  \
        break;  \
    case 0x1e99:  \
        *specptr = unigen_special_0x1e99;  \
        break;  \
    default:  \
        *specptr = NULL;  \
}

#define RETURN_COMBINING_CLASS(ch)  \
switch ((glui32)(ch) >> 8) {  \
  case 3:  \
    switch (ch) {  \
      case 820:  \
      case 821:  \
      case 822:  \
      case 823:  \
      case 824:  \
        return 1;  \
      case 801:  \
      case 802:  \
      case 807:  \
      case 808:  \
        return 202;  \
      case 795:  \
        return 216;  \
      case 790:  \
      case 791:  \
      case 792:  \
      case 793:  \
      case 796:  \
      case 797:  \
      case 798:  \
      case 799:  \
      case 800:  \
      case 803:  \
      case 804:  \
      case 805:  \
      case 806:  \
      case 809:  \
      case 810:  \
      case 811:  \
      case 812:  \
      case 813:  \
      case 814:  \
      case 815:  \
      case 816:  \
      case 817:  \
      case 818:  \
      case 819:  \
      case 825:  \
      case 826:  \
      case 827:  \
      case 828:  \
      case 839:  \
      case 840:  \
      case 841:  \
      case 845:  \
      case 846:  \
      case 851:  \
      case 852:  \
      case 853:  \
      case 854:  \
      case 857:  \
      case 858:  \
        return 220;  \
      case 768:  \
      case 769:  \
      case 770:  \
      case 771:  \
      case 772:  \
      case 773:  \
      case 774:  \
      case 775:  \
      case 776:  \
      case 777:  \
      case 778:  \
      case 779:  \
      case 780:  \
      case 781:  \
      case 782:  \
      case 783:  \
      case 784:  \
      case 785:  \
      case 786:  \
      case 787:  \
      case 788:  \
      case 829:  \
      case 830:  \
      case 831:  \
      case 832:  \
      case 833:  \
      case 834:  \
      case 835:  \
      case 836:  \
      case 838:  \
      case 842:  \
      case 843:  \
      case 844:  \
      case 848:  \
      case 849:  \
      case 850:  \
      case 855:  \
      case 859:  \
      case 867:  \
      case 868:  \
      case 869:  \
      case 870:  \
      case 871:  \
      case 872:  \
      case 873:  \
      case 874:  \
      case 875:  \
      case 876:  \
      case 877:  \
      case 878:  \
      case 879:  \
        return 230;  \
      case 789:  \
      case 794:  \
      case 856:  \
        return 232;  \
      case 860:  \
      case 863:  \
      case 866:  \
        return 233;  \
      case 861:  \
      case 862:  \
      case 864:  \
      case 865:  \
        return 234;  \
      case 837:  \
        return 240;  \
    }  \
    return 0;  \
}  \
return 0;

#define RETURN_COMPOSITION(ch1, ch2)  \
switch ((glui32)(ch1) >> 8) {  \
  case 0:  \
    switch (ch1) {  \
      case 65:  \
        switch (ch2) {  \
          case 768: return 192;  \
          case 769: return 193;  \
          case 770: return 194;  \
          case 771: return 195;  \
          case 772: return 256;  \
          case 774: return 258;  \
          case 775: return 550;  \
          case 776: return 196;  \
          case 777: return 7842;  \
          case 778: return 197;  \
          case 780: return 461;  \
          case 783: return 512;  \
          case 785: return 514;  \
          case 803: return 7840;  \
          case 805: return 7680;  \
          case 808: return 260;  \
        }  \
        return 0;  \
      case 66:  \
        switch (ch2) {  \
          case 775: return 7682;  \
          case 803: return 7684;  \
          case 817: return 7686;  \
        }  \
        return 0;  \
      case 67:  \
        switch (ch2) {  \
          case 769: return 262;  \
          case 770: return 264;  \
          case 775: return 266;  \
          case 780: return 268;  \
          case 807: return 199;  \
        }  \
        return 0;  \
      case 68:  \
        switch (ch2) {  \
          case 775: return 7690;  \
          case 780: return 270;  \
          case 803: return 7692;  \
          case 807: return 7696;  \
          case 813: return 7698;  \
          case 817: return 7694;  \
        }  \
        return 0;  \
      case 69:  \
        switch (ch2) {  \
          case 768: return 200;  \
          case 769: return 201;  \
          case 770: return 202;  \
          case 771: return 7868;  \
          case 772: return 274;  \
          case 774: return 276;  \
          case 775: return 278;  \
          case 776: return 203;  \
          case 777: return 7866;  \
          case 780: return 282;  \
          case 783: return 516;  \
          case 785: return 518;  \
          case 803: return 7864;  \
          case 807: return 552;  \
          case 808: return 280;  \
          case 813: return 7704;  \
          case 816: return 7706;  \
        }  \
        return 0;  \
      case 70:  \
        switch (ch2) {  \
          case 775: return 7710;  \
        }  \
        return 0;  \
      case 71:  \
        switch (ch2) {  \
          case 769: return 500;  \
          case 770: return 284;  \
          case 772: return 7712;  \
          case 774: return 286;  \
          case 775: return 288;  \
          case 780: return 486;  \
          case 807: return 290;  \
        }  \
        return 0;  \
      case 72:  \
        switch (ch2) {  \
          case 770: return 292;  \
          case 775: return 7714;  \
          case 776: return 7718;  \
          case 780: return 542;  \
          case 803: return 7716;  \
          case 807: return 7720;  \
          case 814: return 7722;  \
        }  \
        return 0;  \
      case 73:  \
        switch (ch2) {  \
          case 768: return 204;  \
          case 769: return 205;  \
          case 770: return 206;  \
          case 771: return 296;  \
          case 772: return 298;  \
          case 774: return 300;  \
          case 775: return 304;  \
          case 776: return 207;  \
          case 777: return 7880;  \
          case 780: return 463;  \
          case 783: return 520;  \
          case 785: return 522;  \
          case 803: return 7882;  \
          case 808: return 302;  \
          case 816: return 7724;  \
        }  \
        return 0;  \
      case 74:  \
        switch (ch2) {  \
          case 770: return 308;  \
        }  \
        return 0;  \
      case 75:  \
        switch (ch2) {  \
          case 769: return 7728;  \
          case 780: return 488;  \
          case 803: return 7730;  \
          case 807: return 310;  \
          case 817: return 7732;  \
        }  \
        return 0;  \
      case 76:  \
        switch (ch2) {  \
          case 769: return 313;  \
          case 780: return 317;  \
          case 803: return 7734;  \
          case 807: return 315;  \
          case 813: return 7740;  \
          case 817: return 7738;  \
        }  \
        return 0;  \
      case 77:  \
        switch (ch2) {  \
          case 769: return 7742;  \
          case 775: return 7744;  \
          case 803: return 7746;  \
        }  \
        return 0;  \
      case 78:  \
        switch (ch2) {  \
          case 768: return 504;  \
          case 769: return 323;  \
          case 771: return 209;  \
          case 775: return 7748;  \
          case 780: return 327;  \
          case 803: return 7750;  \
          case 807: return 325;  \
          case 813: return 7754;  \
          case 817: return 7752;  \
        }  \
        return 0;  \
      case 79:  \
        switch (ch2) {  \
          case 768: return 210;  \
          case 769: return 211;  \
          case 770: return 212;  \
          case 771: return 213;  \
          case 772: return 332;  \
          case 774: return 334;  \
          case 775: return 558;  \
          case 776: return 214;  \
          case 777: return 7886;  \
          case 779: return 336;  \
          case 780: return 465;  \
          case 783: return 524;  \
          case 785: return 526;  \
          case 795: return 416;  \
          case 803: return 7884;  \
          case 808: return 490;  \
        }  \
        return 0;  \
      case 80:  \
        switch (ch2) {  \
          case 769: return 7764;  \
          case 775: return 7766;  \
        }  \
        return 0;  \
      case 82:  \
        switch (ch2) {  \
          case 769: return 340;  \
          case 775: return 7768;  \
          case 780: return 344;  \
          case 783: return 528;  \
          case 785: return 530;  \
          case 803: return 7770;  \
          case 807: return 342;  \
          case 817: return 7774;  \
        }  \
        return 0;  \
      case 83:  \
        switch (ch2) {  \
          case 769: return 346;  \
          case 770: return 348;  \
          case 775: return 7776;  \
          case 780: return 352;  \
          case 803: return 7778;  \
          case 806: return 536;  \
          case 807: return 350;  \
        }  \
        return 0;  \
      case 84:  \
        switch (ch2) {  \
          case 775: return 7786;  \
          case 780: return 356;  \
          case 803: return 7788;  \
          case 806: return 538;  \
          case 807: return 354;  \
          case 813: return 7792;  \
          case 817: return 7790;  \
        }  \
        return 0;  \
      case 85:  \
        switch (ch2) {  \
          case 768: return 217;  \
          case 769: return 218;  \
          case 770: return 219;  \
          case 771: return 360;  \
          case 772: return 362;  \
          case 774: return 364;  \
          case 776: return 220;  \
          case 777: return 7910;  \
          case 778: return 366;  \
          case 779: return 368;  \
          case 780: return 467;  \
          case 783: return 532;  \
          case 785: return 534;  \
          case 795: return 431;  \
          case 803: return 7908;  \
          case 804: return 7794;  \
          case 808: return 370;  \
          case 813: return 7798;  \
          case 816: return 7796;  \
        }  \
        return 0;  \
      case 86:  \
        switch (ch2) {  \
          case 771: return 7804;  \
          case 803: return 7806;  \
        }  \
        return 0;  \
      case 87:  \
        switch (ch2) {  \
          case 768: return 7808;  \
          case 769: return 7810;  \
          case 770: return 372;  \
          case 775: return 7814;  \
          case 776: return 7812;  \
          case 803: return 7816;  \
        }  \
        return 0;  \
      case 88:  \
        switch (ch2) {  \
          case 775: return 7818;  \
          case 776: return 7820;  \
        }  \
        return 0;  \
      case 89:  \
        switch (ch2) {  \
          case 768: return 7922;  \
          case 769: return 221;  \
          case 770: return 374;  \
          case 771: return 7928;  \
          case 772: return 562;  \
          case 775: return 7822;  \
          case 776: return 376;  \
          case 777: return 7926;  \
          case 803: return 7924;  \
        }  \
        return 0;  \
      case 90:  \
        switch (ch2) {  \
          case 769: return 377;  \
          case 770: return 7824;  \
          case 775: return 379;  \
          case 780: return 381;  \
          case 803: return 7826;  \
          case 817: return 7828;  \
        }  \
        return 0;  \
      case 97:  \
        switch (ch2) {  \
          case 768: return 224;  \
          case 769: return 225;  \
          case 770: return 226;  \
          case 771: return 227;  \
          case 772: return 257;  \
          case 774: return 259;  \
          case 775: return 551;  \
          case 776: return 228;  \
          case 777: return 7843;  \
          case 778: return 229;  \
          case 780: return 462;  \
          case 783: return 513;  \
          case 785: return 515;  \
          case 803: return 7841;  \
          case 805: return 7681;  \
          case 808: return 261;  \
        }  \
        return 0;  \
      case 98:  \
        switch (ch2) {  \
          case 775: return 7683;  \
          case 803: return 7685;  \
          case 817: return 7687;  \
        }  \
        return 0;  \
      case 99:  \
        switch (ch2) {  \
          case 769: return 263;  \
          case 770: return 265;  \
          case 775: return 267;  \
          case 780: return 269;  \
          case 807: return 231;  \
        }  \
        return 0;  \
      case 100:  \
        switch (ch2) {  \
          case 775: return 7691;  \
          case 780: return 271;  \
          case 803: return 7693;  \
          case 807: return 7697;  \
          case 813: return 7699;  \
          case 817: return 7695;  \
        }  \
        return 0;  \
      case 101:  \
        switch (ch2) {  \
          case 768: return 232;  \
          case 769: return 233;  \
          case 770: return 234;  \
          case 771: return 7869;  \
          case 772: return 275;  \
          case 774: return 277;  \
          case 775: return 279;  \
          case 776: return 235;  \
          case 777: return 7867;  \
          case 780: return 283;  \
          case 783: return 517;  \
          case 785: return 519;  \
          case 803: return 7865;  \
          case 807: return 553;  \
          case 808: return 281;  \
          case 813: return 7705;  \
          case 816: return 7707;  \
        }  \
        return 0;  \
      case 102:  \
        switch (ch2) {  \
          case 775: return 7711;  \
        }  \
        return 0;  \
      case 103:  \
        switch (ch2) {  \
          case 769: return 501;  \
          case 770: return 285;  \
          case 772: return 7713;  \
          case 774: return 287;  \
          case 775: return 289;  \
          case 780: return 487;  \
          case 807: return 291;  \
        }  \
        return 0;  \
      case 104:  \
        switch (ch2) {  \
          case 770: return 293;  \
          case 775: return 7715;  \
          case 776: return 7719;  \
          case 780: return 543;  \
          case 803: return 7717;  \
          case 807: return 7721;  \
          case 814: return 7723;  \
          case 817: return 7830;  \
        }  \
        return 0;  \
      case 105:  \
        switch (ch2) {  \
          case 768: return 236;  \
          case 769: return 237;  \
          case 770: return 238;  \
          case 771: return 297;  \
          case 772: return 299;  \
          case 774: return 301;  \
          case 776: return 239;  \
          case 777: return 7881;  \
          case 780: return 464;  \
          case 783: return 521;  \
          case 785: return 523;  \
          case 803: return 7883;  \
          case 808: return 303;  \
          case 816: return 7725;  \
        }  \
        return 0;  \
      case 106:  \
        switch (ch2) {  \
          case 770: return 309;  \
          case 780: return 496;  \
        }  \
        return 0;  \
      case 107:  \
        switch (ch2) {  \
          case 769: return 7729;  \
          case 780: return 489;  \
          case 803: return 7731;  \
          case 807: return 311;  \
          case 817: return 7733;  \
        }  \
        return 0;  \
      case 108:  \
        switch (ch2) {  \
          case 769: return 314;  \
          case 780: return 318;  \
          case 803: return 7735;  \
          case 807: return 316;  \
          case 813: return 7741;  \
          case 817: return 7739;  \
        }  \
        return 0;  \
      case 109:  \
        switch (ch2) {  \
          case 769: return 7743;  \
          case 775: return 7745;  \
          case 803: return 7747;  \
        }  \
        return 0;  \
      case 110:  \
        switch (ch2) {  \
          case 768: return 505;  \
          case 769: return 324;  \
          case 771: return 241;  \
          case 775: return 7749;  \
          case 780: return 328;  \
          case 803: return 7751;  \
          case 807: return 326;  \
          case 813: return 7755;  \
          case 817: return 7753;  \
        }  \
        return 0;  \
      case 111:  \
        switch (ch2) {  \
          case 768: return 242;  \
          case 769: return 243;  \
          case 770: return 244;  \
          case 771: return 245;  \
          case 772: return 333;  \
          case 774: return 335;  \
          case 775: return 559;  \
          case 776: return 246;  \
          case 777: return 7887;  \
          case 779: return 337;  \
          case 780: return 466;  \
          case 783: return 525;  \
          case 785: return 527;  \
          case 795: return 417;  \
          case 803: return 7885;  \
          case 808: return 491;  \
        }  \
        return 0;  \
      case 112:  \
        switch (ch2) {  \
          case 769: return 7765;  \
          case 775: return 7767;  \
        }  \
        return 0;  \
      case 114:  \
        switch (ch2) {  \
          case 769: return 341;  \
          case 775: return 7769;  \
          case 780: return 345;  \
          case 783: return 529;  \
          case 785: return 531;  \
          case 803: return 7771;  \
          case 807: return 343;  \
          case 817: return 7775;  \
        }  \
        return 0;  \
      case 115:  \
        switch (ch2) {  \
          case 769: return 347;  \
          case 770: return 349;  \
          case 775: return 7777;  \
          case 780: return 353;  \
          case 803: return 7779;  \
          case 806: return 537;  \
          case 807: return 351;  \
        }  \
        return 0;  \
      case 116:  \
        switch (ch2) {  \
          case 775: return 7787;  \
          case 776: return 7831;  \
          case 780: return 357;  \
          case 803: return 7789;  \
          case 806: return 539;  \
          case 807: return 355;  \
          case 813: return 7793;  \
          case 817: return 7791;  \
        }  \
        return 0;  \
      case 117:  \
        switch (ch2) {  \
          case 768: return 249;  \
          case 769: return 250;  \
          case 770: return 251;  \
          case 771: return 361;  \
          case 772: return 363;  \
          case 774: return 365;  \
          case 776: return 252;  \
          case 777: return 7911;  \
          case 778: return 367;  \
          case 779: return 369;  \
          case 780: return 468;  \
          case 783: return 533;  \
          case 785: return 535;  \
          case 795: return 432;  \
          case 803: return 7909;  \
          case 804: return 7795;  \
          case 808: return 371;  \
          case 813: return 7799;  \
          case 816: return 7797;  \
        }  \
        return 0;  \
      case 118:  \
        switch (ch2) {  \
          case 771: return 7805;  \
          case 803: return 7807;  \
        }  \
        return 0;  \
      case 119:  \
        switch (ch2) {  \
          case 768: return 7809;  \
          case 769: return 7811;  \
          case 770: return 373;  \
          case 775: return 7815;  \
          case 776: return 7813;  \
          case 778: return 7832;  \
          case 803: return 7817;  \
        }  \
        return 0;  \
      case 120:  \
        switch (ch2) {  \
          case 775: return 7819;  \
          case 776: return 7821;  \
        }  \
        return 0;  \
      case 121:  \
        switch (ch2) {  \
          case 768: return 7923;  \
          case 769: return 253;  \
          case 770: return 375;  \
          case 771: return 7929;  \
          case 772: return 563;  \
          case 775: return 7823;  \
          case 776: return 255;  \
          case 777: return 7927;  \
          case 778: return 7833;  \
          case 803: return 7925;  \
        }  \
        return 0;  \
      case 122:  \
        switch (ch2) {  \
          case 769: return 378;  \
          case 770: return 7825;  \
          case 775: return 380;  \
          case 780: return 382;  \
          case 803: return 7827;  \
          case 817: return 7829;  \
        }  \
        return 0;  \
      case 194:  \
        switch (ch2) {  \
          case 768: return 7846;  \
          case 769: return 7844;  \
          case 771: return 7850;  \
          case 777: return 7848;  \
        }  \
        return 0;  \
      case 196:  \
        switch (ch2) {  \
          case 772: return 478;  \
        }  \
        return 0;  \
      case 197:  \
        switch (ch2) {  \
          case 769: return 506;  \
        }  \
        return 0;  \
      case 198:  \
        switch (ch2) {  \
          case 769: return 508;  \
          case 772: return 482;  \
        }  \
        return 0;  \
      case 199:  \
        switch (ch2) {  \
          case 769: return 7688;  \
        }  \
        return 0;  \
      case 202:  \
        switch (ch2) {  \
          case 768: return 7872;  \
          case 769: return 7870;  \
          case 771: return 7876;  \
          case 777: return 7874;  \
        }  \
        return 0;  \
      case 207:  \
        switch (ch2) {  \
          case 769: return 7726;  \
        }  \
        return 0;  \
      case 212:  \
        switch (ch2) {  \
          case 768: return 7890;  \
          case 769: return 7888;  \
          case 771: return 7894;  \
          case 777: return 7892;  \
        }  \
        return 0;  \
      case 213:  \
        switch (ch2) {  \
          case 769: return 7756;  \
          case 772: return 556;  \
          case 776: return 7758;  \
        }  \
        return 0;  \
      case 214:  \
        switch (ch2) {  \
          case 772: return 554;  \
        }  \
        return 0;  \
      case 216:  \
        switch (ch2) {  \
          case 769: return 510;  \
        }  \
        return 0;  \
      case 220:  \
        switch (ch2) {  \
          case 768: return 475;  \
          case 769: return 471;  \
          case 772: return 469;  \
          case 780: return 473;  \
        }  \
        return 0;  \
      case 226:  \
        switch (ch2) {  \
          case 768: return 7847;  \
          case 769: return 7845;  \
          case 771: return 7851;  \
          case 777: return 7849;  \
        }  \
        return 0;  \
      case 228:  \
        switch (ch2) {  \
          case 772: return 479;  \
        }  \
        return 0;  \
      case 229:  \
        switch (ch2) {  \
          case 769: return 507;  \
        }  \
        return 0;  \
      case 230:  \
        switch (ch2) {  \
          case 769: return 509;  \
          case 772: return 483;  \
        }  \
        return 0;  \
      case 231:  \
        switch (ch2) {  \
          case 769: return 7689;  \
        }  \
        return 0;  \
      case 234:  \
        switch (ch2) {  \
          case 768: return 7873;  \
          case 769: return 7871;  \
          case 771: return 7877;  \
          case 777: return 7875;  \
        }  \
        return 0;  \
      case 239:  \
        switch (ch2) {  \
          case 769: return 7727;  \
        }  \
        return 0;  \
      case 244:  \
        switch (ch2) {  \
          case 768: return 7891;  \
          case 769: return 7889;  \
          case 771: return 7895;  \
          case 777: return 7893;  \
        }  \
        return 0;  \
      case 245:  \
        switch (ch2) {  \
          case 769: return 7757;  \
          case 772: return 557;  \
          case 776: return 7759;  \
        }  \
        return 0;  \
      case 246:  \
        switch (ch2) {  \
          case 772: return 555;  \
        }  \
        return 0;  \
      case 248:  \
        switch (ch2) {  \
          case 769: return 511;  \
        }  \
        return 0;  \
      case 252:  \
        switch (ch2) {  \
          case 768: return 476;  \
          case 769: return 472;  \
          case 772: return 470;  \
          case 780: return 474;  \
        }  \
        return 0;  \
    }  \
    return 0;  \
  case 1:  \
    switch (ch1) {  \
      case 258:  \
        switch (ch2) {  \
          case 768: return 7856;  \
          case 769: return 7854;  \
          case 771: return 7860;  \
          case 777: return 7858;  \
        }  \
        return 0;  \
      case 259:  \
        switch (ch2) {  \
          case 768: return 7857;  \
          case 769: return 7855;  \
          case 771: return 7861;  \
          case 777: return 7859;  \
        }  \
        return 0;  \
      case 274:  \
        switch (ch2) {  \
          case 768: return 7700;  \
          case 769: return 7702;  \
        }  \
        return 0;  \
      case 275:  \
        switch (ch2) {  \
          case 768: return 7701;  \
          case 769: return 7703;  \
        }  \
        return 0;  \
      case 332:  \
        switch (ch2) {  \
          case 768: return 7760;  \
          case 769: return 7762;  \
        }  \
        return 0;  \
      case 333:  \
        switch (ch2) {  \
          case 768: return 7761;  \
          case 769: return 7763;  \
        }  \
        return 0;  \
      case 346:  \
        switch (ch2) {  \
          case 775: return 7780;  \
        }  \
        return 0;  \
      case 347:  \
        switch (ch2) {  \
          case 775: return 7781;  \
        }  \
        return 0;  \
      case 352:  \
        switch (ch2) {  \
          case 775: return 7782;  \
        }  \
        return 0;  \
      case 353:  \
        switch (ch2) {  \
          case 775: return 7783;  \
        }  \
        return 0;  \
      case 360:  \
        switch (ch2) {  \
          case 769: return 7800;  \
        }  \
        return 0;  \
      case 361:  \
        switch (ch2) {  \
          case 769: return 7801;  \
        }  \
        return 0;  \
      case 362:  \
        switch (ch2) {  \
          case 776: return 7802;  \
        }  \
        return 0;  \
      case 363:  \
        switch (ch2) {  \
          case 776: return 7803;  \
        }  \
        return 0;  \
      case 383:  \
        switch (ch2) {  \
          case 775: return 7835;  \
        }  \
        return 0;  \
      case 416:  \
        switch (ch2) {  \
          case 768: return 7900;  \
          case 769: return 7898;  \
          case 771: return 7904;  \
          case 777: return 7902;  \
          case 803: return 7906;  \
        }  \
        return 0;  \
      case 417:  \
        switch (ch2) {  \
          case 768: return 7901;  \
          case 769: return 7899;  \
          case 771: return 7905;  \
          case 777: return 7903;  \
          case 803: return 7907;  \
        }  \
        return 0;  \
      case 431:  \
        switch (ch2) {  \
          case 768: return 7914;  \
          case 769: return 7912;  \
          case 771: return 7918;  \
          case 777: return 7916;  \
          case 803: return 7920;  \
        }  \
        return 0;  \
      case 432:  \
        switch (ch2) {  \
          case 768: return 7915;  \
          case 769: return 7913;  \
          case 771: return 7919;  \
          case 777: return 7917;  \
          case 803: return 7921;  \
        }  \
        return 0;  \
      case 439:  \
        switch (ch2) {  \
          case 780: return 494;  \
        }  \
        return 0;  \
      case 490:  \
        switch (ch2) {  \
          case 772: return 492;  \
        }  \
        return 0;  \
      case 491:  \
        switch (ch2) {  \
          case 772: return 493;  \
        }  \
        return 0;  \
    }  \
    return 0;  \
  case 2:  \
    switch (ch1) {  \
      case 550:  \
        switch (ch2) {  \
          case 772: return 480;  \
        }  \
        return 0;  \
      case 551:  \
        switch (ch2) {  \
          case 772: return 481;  \
        }  \
        return 0;  \
      case 552:  \
        switch (ch2) {  \
          case 774: return 7708;  \
        }  \
        return 0;  \
      case 553:  \
        switch (ch2) {  \
          case 774: return 7709;  \
        }  \
        return 0;  \
      case 558:  \
        switch (ch2) {  \
          case 772: return 560;  \
        }  \
        return 0;  \
      case 559:  \
        switch (ch2) {  \
          case 772: return 561;  \
        }  \
        return 0;  \
      case 658:  \
        switch (ch2) {  \
          case 780: return 495;  \
        }  \
        return 0;  \
    }  \
    return 0;  \
  case 3:  \
    switch (ch1) {  \
      case 776:  \
        switch (ch2) {  \
          case 769: return 836;  \
        }  \
        return 0;  \
    }  \
    return 0;  \
  case 30:  \
    switch (ch1) {  \
      case 7734:  \
        switch (ch2) {  \
          case 772: return 7736;  \
        }  \
        return 0;  \
      case 7735:  \
        switch (ch2) {  \
          case 772: return 7737;  \
        }  \
        return 0;  \
      case 7770:  \
        switch (ch2) {  \
          case 772: return 7772;  \
        }  \
        return 0;  \
      case 7771:  \
        switch (ch2) {  \
          case 772: return 7773;  \
        }  \
        return 0;  \
      case 7778:  \
        switch (ch2) {  \
          case 775: return 7784;  \
        }  \
        return 0;  \
      case 7779:  \
        switch (ch2) {  \
          case 775: return 7785;  \
        }  \
        return 0;  \
      case 7840:  \
        switch (ch2) {  \
          case 770: return 7852;  \
          case 774: return 7862;  \
        }  \
        return 0;  \
      case 7841:  \
        switch (ch2) {  \
          case 770: return 7853;  \
          case 774: return 7863;  \
        }  \
        return 0;  \
      case 7864:  \
        switch (ch2) {  \
          case 770: return 7878;  \
        }  \
        return 0;  \
      case 7865:  \
        switch (ch2) {  \
          case 770: return 7879;  \
        }  \
        return 0;  \
      case 7884:  \
        switch (ch2) {  \
          case 770: return 7896;  \
        }  \
        return 0;  \
      case 7885:  \
        switch (ch2) {  \
          case 770: return 7897;  \
        }  \
        return 0;  \
    }  \
    return 0;  \
}  \
return 0;

static glui32 unigen_decomp_data[1113] = {
0x41, 0x300, 0x41, 0x301, 0x41, 0x302, 0x41, 0x303, 
0x41, 0x308, 0x41, 0x30a, 0x43, 0x327, 0x45, 0x300, 
0x45, 0x301, 0x45, 0x302, 0x45, 0x308, 0x49, 0x300, 
0x49, 0x301, 0x49, 0x302, 0x49, 0x308, 0x4e, 0x303, 
0x4f, 0x300, 0x4f, 0x301, 0x4f, 0x302, 0x4f, 0x303, 
0x4f, 0x308, 0x55, 0x300, 0x55, 0x301, 0x55, 0x302, 
0x55, 0x308, 0x59, 0x301, 0x61, 0x300, 0x61, 0x301, 
0x61, 0x302, 0x61, 0x303, 0x61, 0x308, 0x61, 0x30a, 
0x63, 0x327, 0x65, 0x300, 0x65, 0x301, 0x65, 0x302, 
0x65, 0x308, 0x69, 0x300, 0x69, 0x301, 0x69, 0x302, 
0x69, 0x308, 0x6e, 0x303, 0x6f, 0x300, 0x6f, 0x301, 
0x6f, 0x302, 0x6f, 0x303, 0x6f, 0x308, 0x75, 0x300, 
0x75, 0x301, 0x75, 0x302, 0x75, 0x308, 0x79, 0x301, 
0x79, 0x308, 0x41, 0x304, 0x61, 0x304, 0x41, 0x306, 
0x61, 0x306, 0x41, 0x328, 0x61, 0x328, 0x43, 0x301, 
0x63, 0x301, 0x43, 0x302, 0x63, 0x302, 0x43, 0x307, 
0x63, 0x307, 0x43, 0x30c, 0x63, 0x30c, 0x44, 0x30c, 
0x64, 0x30c, 0x45, 0x304, 0x65, 0x304, 0x45, 0x306, 
0x65, 0x306, 0x45, 0x307, 0x65, 0x307, 0x45, 0x328, 
0x65, 0x328, 0x45, 0x30c, 0x65, 0x30c, 0x47, 0x302, 
0x67, 0x302, 0x47, 0x306, 0x67, 0x306, 0x47, 0x307, 
0x67, 0x307, 0x47, 0x327, 0x67, 0x327, 0x48, 0x302, 
0x68, 0x302, 0x49, 0x303, 0x69, 0x303, 0x49, 0x304, 
0x69, 0x304, 0x49, 0x306, 0x69, 0x306, 0x49, 0x328, 
0x69, 0x328, 0x49, 0x307, 0x4a, 0x302, 0x6a, 0x302, 
0x4b, 0x327, 0x6b, 0x327, 0x4c, 0x301, 0x6c, 0x301, 
0x4c, 0x327, 0x6c, 0x327, 0x4c, 0x30c, 0x6c, 0x30c, 
0x4e, 0x301, 0x6e, 0x301, 0x4e, 0x327, 0x6e, 0x327, 
0x4e, 0x30c, 0x6e, 0x30c, 0x4f, 0x304, 0x6f, 0x304, 
0x4f, 0x306, 0x6f, 0x306, 0x4f, 0x30b, 0x6f, 0x30b, 
0x52, 0x301, 0x72, 0x301, 0x52, 0x327, 0x72, 0x327, 
0x52, 0x30c, 0x72, 0x30c, 0x53, 0x301, 0x73, 0x301, 
0x53, 0x302, 0x73, 0x302, 0x53, 0x327, 0x73, 0x327, 
0x53, 0x30c, 0x73, 0x30c, 0x54, 0x327, 0x74, 0x327, 
0x54, 0x30c, 0x74, 0x30c, 0x55, 0x303, 0x75, 0x303, 
0x55, 0x304, 0x75, 0x304, 0x55, 0x306, 0x75, 0x306, 
0x55, 0x30a, 0x75, 0x30a, 0x55, 0x30b, 0x75, 0x30b, 
0x55, 0x328, 0x75, 0x328, 0x57, 0x302, 0x77, 0x302, 
0x59, 0x302, 0x79, 0x302, 0x59, 0x308, 0x5a, 0x301, 
0x7a, 0x301, 0x5a, 0x307, 0x7a, 0x307, 0x5a, 0x30c, 
0x7a, 0x30c, 0x4f, 0x31b, 0x6f, 0x31b, 0x55, 0x31b, 
0x75, 0x31b, 0x41, 0x30c, 0x61, 0x30c, 0x49, 0x30c, 
0x69, 0x30c, 0x4f, 0x30c, 0x6f, 0x30c, 0x55, 0x30c, 
0x75, 0x30c, 0x55, 0x308, 0x304, 0x75, 0x308, 0x304, 
0x55, 0x308, 0x301, 0x75, 0x308, 0x301, 0x55, 0x308, 
0x30c, 0x75, 0x308, 0x30c, 0x55, 0x308, 0x300, 0x75, 
0x308, 0x300, 0x41, 0x308, 0x304, 0x61, 0x308, 0x304, 
0x41, 0x307, 0x304, 0x61, 0x307, 0x304, 0xc6, 0x304, 
0xe6, 0x304, 0x47, 0x30c, 0x67, 0x30c, 0x4b, 0x30c, 
0x6b, 0x30c, 0x4f, 0x328, 0x6f, 0x328, 0x4f, 0x328, 
0x304, 0x6f, 0x328, 0x304, 0x1b7, 0x30c, 0x292, 0x30c, 
0x6a, 0x30c, 0x47, 0x301, 0x67, 0x301, 0x4e, 0x300, 
0x6e, 0x300, 0x41, 0x30a, 0x301, 0x61, 0x30a, 0x301, 
0xc6, 0x301, 0xe6, 0x301, 0xd8, 0x301, 0xf8, 0x301, 
0x41, 0x30f, 0x61, 0x30f, 0x41, 0x311, 0x61, 0x311, 
0x45, 0x30f, 0x65, 0x30f, 0x45, 0x311, 0x65, 0x311, 
0x49, 0x30f, 0x69, 0x30f, 0x49, 0x311, 0x69, 0x311, 
0x4f, 0x30f, 0x6f, 0x30f, 0x4f, 0x311, 0x6f, 0x311, 
0x52, 0x30f, 0x72, 0x30f, 0x52, 0x311, 0x72, 0x311, 
0x55, 0x30f, 0x75, 0x30f, 0x55, 0x311, 0x75, 0x311, 
0x53, 0x326, 0x73, 0x326, 0x54, 0x326, 0x74, 0x326, 
0x48, 0x30c, 0x68, 0x30c, 0x41, 0x307, 0x61, 0x307, 
0x45, 0x327, 0x65, 0x327, 0x4f, 0x308, 0x304, 0x6f, 
0x308, 0x304, 0x4f, 0x303, 0x304, 0x6f, 0x303, 0x304, 
0x4f, 0x307, 0x6f, 0x307, 0x4f, 0x307, 0x304, 0x6f, 
0x307, 0x304, 0x59, 0x304, 0x79, 0x304, 0x300, 0x301, 
0x313, 0x308, 0x301, 0x41, 0x325, 0x61, 0x325, 0x42, 
0x307, 0x62, 0x307, 0x42, 0x323, 0x62, 0x323, 0x42, 
0x331, 0x62, 0x331, 0x43, 0x327, 0x301, 0x63, 0x327, 
0x301, 0x44, 0x307, 0x64, 0x307, 0x44, 0x323, 0x64, 
0x323, 0x44, 0x331, 0x64, 0x331, 0x44, 0x327, 0x64, 
0x327, 0x44, 0x32d, 0x64, 0x32d, 0x45, 0x304, 0x300, 
0x65, 0x304, 0x300, 0x45, 0x304, 0x301, 0x65, 0x304, 
0x301, 0x45, 0x32d, 0x65, 0x32d, 0x45, 0x330, 0x65, 
0x330, 0x45, 0x327, 0x306, 0x65, 0x327, 0x306, 0x46, 
0x307, 0x66, 0x307, 0x47, 0x304, 0x67, 0x304, 0x48, 
0x307, 0x68, 0x307, 0x48, 0x323, 0x68, 0x323, 0x48, 
0x308, 0x68, 0x308, 0x48, 0x327, 0x68, 0x327, 0x48, 
0x32e, 0x68, 0x32e, 0x49, 0x330, 0x69, 0x330, 0x49, 
0x308, 0x301, 0x69, 0x308, 0x301, 0x4b, 0x301, 0x6b, 
0x301, 0x4b, 0x323, 0x6b, 0x323, 0x4b, 0x331, 0x6b, 
0x331, 0x4c, 0x323, 0x6c, 0x323, 0x4c, 0x323, 0x304, 
0x6c, 0x323, 0x304, 0x4c, 0x331, 0x6c, 0x331, 0x4c, 
0x32d, 0x6c, 0x32d, 0x4d, 0x301, 0x6d, 0x301, 0x4d, 
0x307, 0x6d, 0x307, 0x4d, 0x323, 0x6d, 0x323, 0x4e, 
0x307, 0x6e, 0x307, 0x4e, 0x323, 0x6e, 0x323, 0x4e, 
0x331, 0x6e, 0x331, 0x4e, 0x32d, 0x6e, 0x32d, 0x4f, 
0x303, 0x301, 0x6f, 0x303, 0x301, 0x4f, 0x303, 0x308, 
0x6f, 0x303, 0x308, 0x4f, 0x304, 0x300, 0x6f, 0x304, 
0x300, 0x4f, 0x304, 0x301, 0x6f, 0x304, 0x301, 0x50, 
0x301, 0x70, 0x301, 0x50, 0x307, 0x70, 0x307, 0x52, 
0x307, 0x72, 0x307, 0x52, 0x323, 0x72, 0x323, 0x52, 
0x323, 0x304, 0x72, 0x323, 0x304, 0x52, 0x331, 0x72, 
0x331, 0x53, 0x307, 0x73, 0x307, 0x53, 0x323, 0x73, 
0x323, 0x53, 0x301, 0x307, 0x73, 0x301, 0x307, 0x53, 
0x30c, 0x307, 0x73, 0x30c, 0x307, 0x53, 0x323, 0x307, 
0x73, 0x323, 0x307, 0x54, 0x307, 0x74, 0x307, 0x54, 
0x323, 0x74, 0x323, 0x54, 0x331, 0x74, 0x331, 0x54, 
0x32d, 0x74, 0x32d, 0x55, 0x324, 0x75, 0x324, 0x55, 
0x330, 0x75, 0x330, 0x55, 0x32d, 0x75, 0x32d, 0x55, 
0x303, 0x301, 0x75, 0x303, 0x301, 0x55, 0x304, 0x308, 
0x75, 0x304, 0x308, 0x56, 0x303, 0x76, 0x303, 0x56, 
0x323, 0x76, 0x323, 0x57, 0x300, 0x77, 0x300, 0x57, 
0x301, 0x77, 0x301, 0x57, 0x308, 0x77, 0x308, 0x57, 
0x307, 0x77, 0x307, 0x57, 0x323, 0x77, 0x323, 0x58, 
0x307, 0x78, 0x307, 0x58, 0x308, 0x78, 0x308, 0x59, 
0x307, 0x79, 0x307, 0x5a, 0x302, 0x7a, 0x302, 0x5a, 
0x323, 0x7a, 0x323, 0x5a, 0x331, 0x7a, 0x331, 0x68, 
0x331, 0x74, 0x308, 0x77, 0x30a, 0x79, 0x30a, 0x17f, 
0x307, 0x41, 0x323, 0x61, 0x323, 0x41, 0x309, 0x61, 
0x309, 0x41, 0x302, 0x301, 0x61, 0x302, 0x301, 0x41, 
0x302, 0x300, 0x61, 0x302, 0x300, 0x41, 0x302, 0x309, 
0x61, 0x302, 0x309, 0x41, 0x302, 0x303, 0x61, 0x302, 
0x303, 0x41, 0x323, 0x302, 0x61, 0x323, 0x302, 0x41, 
0x306, 0x301, 0x61, 0x306, 0x301, 0x41, 0x306, 0x300, 
0x61, 0x306, 0x300, 0x41, 0x306, 0x309, 0x61, 0x306, 
0x309, 0x41, 0x306, 0x303, 0x61, 0x306, 0x303, 0x41, 
0x323, 0x306, 0x61, 0x323, 0x306, 0x45, 0x323, 0x65, 
0x323, 0x45, 0x309, 0x65, 0x309, 0x45, 0x303, 0x65, 
0x303, 0x45, 0x302, 0x301, 0x65, 0x302, 0x301, 0x45, 
0x302, 0x300, 0x65, 0x302, 0x300, 0x45, 0x302, 0x309, 
0x65, 0x302, 0x309, 0x45, 0x302, 0x303, 0x65, 0x302, 
0x303, 0x45, 0x323, 0x302, 0x65, 0x323, 0x302, 0x49, 
0x309, 0x69, 0x309, 0x49, 0x323, 0x69, 0x323, 0x4f, 
0x323, 0x6f, 0x323, 0x4f, 0x309, 0x6f, 0x309, 0x4f, 
0x302, 0x301, 0x6f, 0x302, 0x301, 0x4f, 0x302, 0x300, 
0x6f, 0x302, 0x300, 0x4f, 0x302, 0x309, 0x6f, 0x302, 
0x309, 0x4f, 0x302, 0x303, 0x6f, 0x302, 0x303, 0x4f, 
0x323, 0x302, 0x6f, 0x323, 0x302, 0x4f, 0x31b, 0x301, 
0x6f, 0x31b, 0x301, 0x4f, 0x31b, 0x300, 0x6f, 0x31b, 
0x300, 0x4f, 0x31b, 0x309, 0x6f, 0x31b, 0x309, 0x4f, 
0x31b, 0x303, 0x6f, 0x31b, 0x303, 0x4f, 0x31b, 0x323, 
0x6f, 0x31b, 0x323, 0x55, 0x323, 0x75, 0x323, 0x55, 
0x309, 0x75, 0x309, 0x55, 0x31b, 0x301, 0x75, 0x31b, 
0x301, 0x55, 0x31b, 0x300, 0x75, 0x31b, 0x300, 0x55, 
0x31b, 0x309, 0x75, 0x31b, 0x309, 0x55, 0x31b, 0x303, 
0x75, 0x31b, 0x303, 0x55, 0x31b, 0x323, 0x75, 0x31b, 
0x323, 0x59, 0x300, 0x79, 0x300, 0x59, 0x323, 0x79, 
0x323, 0x59, 0x309, 0x79, 0x309, 0x59, 0x303, 0x79, 
0x303, };

static gli_decomp_block_t unigen_decomp_block_0x0[256] = {
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 2, 0 },
    { 2, 2 },
    { 2, 4 },
    { 2, 6 },
    { 2, 8 },
    { 2, 10 },
    { 0, 0 },
    { 2, 12 },
    { 2, 14 },
    { 2, 16 },
    { 2, 18 },
    { 2, 20 },
    { 2, 22 },
    { 2, 24 },
    { 2, 26 },
    { 2, 28 },
    { 0, 0 },
    { 2, 30 },
    { 2, 32 },
    { 2, 34 },
    { 2, 36 },
    { 2, 38 },
    { 2, 40 },
    { 0, 0 },
    { 0, 0 },
    { 2, 42 },
    { 2, 44 },
    { 2, 46 },
    { 2, 48 },
    { 2, 50 },
    { 0, 0 },
    { 0, 0 },
    { 2, 52 },
    { 2, 54 },
    { 2, 56 },
    { 2, 58 },
    { 2, 60 },
    { 2, 62 },
    { 0, 0 },
    { 2, 64 },
    { 2, 66 },
    { 2, 68 },
    { 2, 70 },
    { 2, 72 },
    { 2, 74 },
    { 2, 76 },
    { 2, 78 },
    { 2, 80 },
    { 0, 0 },
    { 2, 82 },
    { 2, 84 },
    { 2, 86 },
    { 2, 88 },
    { 2, 90 },
    { 2, 92 },
    { 0, 0 },
    { 0, 0 },
    { 2, 94 },
    { 2, 96 },
    { 2, 98 },
    { 2, 100 },
    { 2, 102 },
    { 0, 0 },
    { 2, 104 },
};

static gli_decomp_block_t unigen_decomp_block_0x1[256] = {
    { 2, 106 },
    { 2, 108 },
    { 2, 110 },
    { 2, 112 },
    { 2, 114 },
    { 2, 116 },
    { 2, 118 },
    { 2, 120 },
    { 2, 122 },
    { 2, 124 },
    { 2, 126 },
    { 2, 128 },
    { 2, 130 },
    { 2, 132 },
    { 2, 134 },
    { 2, 136 },
    { 0, 0 },
    { 0, 0 },
    { 2, 138 },
    { 2, 140 },
    { 2, 142 },
    { 2, 144 },
    { 2, 146 },
    { 2, 148 },
    { 2, 150 },
    { 2, 152 },
    { 2, 154 },
    { 2, 156 },
    { 2, 158 },
    { 2, 160 },
    { 2, 162 },
    { 2, 164 },
    { 2, 166 },
    { 2, 168 },
    { 2, 170 },
    { 2, 172 },
    { 2, 174 },
    { 2, 176 },
    { 0, 0 },
    { 0, 0 },
    { 2, 178 },
    { 2, 180 },
    { 2, 182 },
    { 2, 184 },
    { 2, 186 },
    { 2, 188 },
    { 2, 190 },
    { 2, 192 },
    { 2, 194 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 2, 196 },
    { 2, 198 },
    { 2, 200 },
    { 2, 202 },
    { 0, 0 },
    { 2, 204 },
    { 2, 206 },
    { 2, 208 },
    { 2, 210 },
    { 2, 212 },
    { 2, 214 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 2, 216 },
    { 2, 218 },
    { 2, 220 },
    { 2, 222 },
    { 2, 224 },
    { 2, 226 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 2, 228 },
    { 2, 230 },
    { 2, 232 },
    { 2, 234 },
    { 2, 236 },
    { 2, 238 },
    { 0, 0 },
    { 0, 0 },
    { 2, 240 },
    { 2, 242 },
    { 2, 244 },
    { 2, 246 },
    { 2, 248 },
    { 2, 250 },
    { 2, 252 },
    { 2, 254 },
    { 2, 256 },
    { 2, 258 },
    { 2, 260 },
    { 2, 262 },
    { 2, 264 },
    { 2, 266 },
    { 2, 268 },
    { 2, 270 },
    { 2, 272 },
    { 2, 274 },
    { 0, 0 },
    { 0, 0 },
    { 2, 276 },
    { 2, 278 },
    { 2, 280 },
    { 2, 282 },
    { 2, 284 },
    { 2, 286 },
    { 2, 288 },
    { 2, 290 },
    { 2, 292 },
    { 2, 294 },
    { 2, 296 },
    { 2, 298 },
    { 2, 300 },
    { 2, 302 },
    { 2, 304 },
    { 2, 306 },
    { 2, 308 },
    { 2, 310 },
    { 2, 312 },
    { 2, 314 },
    { 2, 316 },
    { 2, 318 },
    { 2, 320 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 2, 322 },
    { 2, 324 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 2, 326 },
    { 2, 328 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 2, 330 },
    { 2, 332 },
    { 2, 334 },
    { 2, 336 },
    { 2, 338 },
    { 2, 340 },
    { 2, 342 },
    { 2, 344 },
    { 3, 346 },
    { 3, 349 },
    { 3, 352 },
    { 3, 355 },
    { 3, 358 },
    { 3, 361 },
    { 3, 364 },
    { 3, 367 },
    { 0, 0 },
    { 3, 370 },
    { 3, 373 },
    { 3, 376 },
    { 3, 379 },
    { 2, 382 },
    { 2, 384 },
    { 0, 0 },
    { 0, 0 },
    { 2, 386 },
    { 2, 388 },
    { 2, 390 },
    { 2, 392 },
    { 2, 394 },
    { 2, 396 },
    { 3, 398 },
    { 3, 401 },
    { 2, 404 },
    { 2, 406 },
    { 2, 408 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 2, 410 },
    { 2, 412 },
    { 0, 0 },
    { 0, 0 },
    { 2, 414 },
    { 2, 416 },
    { 3, 418 },
    { 3, 421 },
    { 2, 424 },
    { 2, 426 },
    { 2, 428 },
    { 2, 430 },
};

static gli_decomp_block_t unigen_decomp_block_0x2[256] = {
    { 2, 432 },
    { 2, 434 },
    { 2, 436 },
    { 2, 438 },
    { 2, 440 },
    { 2, 442 },
    { 2, 444 },
    { 2, 446 },
    { 2, 448 },
    { 2, 450 },
    { 2, 452 },
    { 2, 454 },
    { 2, 456 },
    { 2, 458 },
    { 2, 460 },
    { 2, 462 },
    { 2, 464 },
    { 2, 466 },
    { 2, 468 },
    { 2, 470 },
    { 2, 472 },
    { 2, 474 },
    { 2, 476 },
    { 2, 478 },
    { 2, 480 },
    { 2, 482 },
    { 2, 484 },
    { 2, 486 },
    { 0, 0 },
    { 0, 0 },
    { 2, 488 },
    { 2, 490 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 2, 492 },
    { 2, 494 },
    { 2, 496 },
    { 2, 498 },
    { 3, 500 },
    { 3, 503 },
    { 3, 506 },
    { 3, 509 },
    { 2, 512 },
    { 2, 514 },
    { 3, 516 },
    { 3, 519 },
    { 2, 522 },
    { 2, 524 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
};

static gli_decomp_block_t unigen_decomp_block_0x1e[256] = {
    { 2, 531 },
    { 2, 533 },
    { 2, 535 },
    { 2, 537 },
    { 2, 539 },
    { 2, 541 },
    { 2, 543 },
    { 2, 545 },
    { 3, 547 },
    { 3, 550 },
    { 2, 553 },
    { 2, 555 },
    { 2, 557 },
    { 2, 559 },
    { 2, 561 },
    { 2, 563 },
    { 2, 565 },
    { 2, 567 },
    { 2, 569 },
    { 2, 571 },
    { 3, 573 },
    { 3, 576 },
    { 3, 579 },
    { 3, 582 },
    { 2, 585 },
    { 2, 587 },
    { 2, 589 },
    { 2, 591 },
    { 3, 593 },
    { 3, 596 },
    { 2, 599 },
    { 2, 601 },
    { 2, 603 },
    { 2, 605 },
    { 2, 607 },
    { 2, 609 },
    { 2, 611 },
    { 2, 613 },
    { 2, 615 },
    { 2, 617 },
    { 2, 619 },
    { 2, 621 },
    { 2, 623 },
    { 2, 625 },
    { 2, 627 },
    { 2, 629 },
    { 3, 631 },
    { 3, 634 },
    { 2, 637 },
    { 2, 639 },
    { 2, 641 },
    { 2, 643 },
    { 2, 645 },
    { 2, 647 },
    { 2, 649 },
    { 2, 651 },
    { 3, 653 },
    { 3, 656 },
    { 2, 659 },
    { 2, 661 },
    { 2, 663 },
    { 2, 665 },
    { 2, 667 },
    { 2, 669 },
    { 2, 671 },
    { 2, 673 },
    { 2, 675 },
    { 2, 677 },
    { 2, 679 },
    { 2, 681 },
    { 2, 683 },
    { 2, 685 },
    { 2, 687 },
    { 2, 689 },
    { 2, 691 },
    { 2, 693 },
    { 3, 695 },
    { 3, 698 },
    { 3, 701 },
    { 3, 704 },
    { 3, 707 },
    { 3, 710 },
    { 3, 713 },
    { 3, 716 },
    { 2, 719 },
    { 2, 721 },
    { 2, 723 },
    { 2, 725 },
    { 2, 727 },
    { 2, 729 },
    { 2, 731 },
    { 2, 733 },
    { 3, 735 },
    { 3, 738 },
    { 2, 741 },
    { 2, 743 },
    { 2, 745 },
    { 2, 747 },
    { 2, 749 },
    { 2, 751 },
    { 3, 753 },
    { 3, 756 },
    { 3, 759 },
    { 3, 762 },
    { 3, 765 },
    { 3, 768 },
    { 2, 771 },
    { 2, 773 },
    { 2, 775 },
    { 2, 777 },
    { 2, 779 },
    { 2, 781 },
    { 2, 783 },
    { 2, 785 },
    { 2, 787 },
    { 2, 789 },
    { 2, 791 },
    { 2, 793 },
    { 2, 795 },
    { 2, 797 },
    { 3, 799 },
    { 3, 802 },
    { 3, 805 },
    { 3, 808 },
    { 2, 811 },
    { 2, 813 },
    { 2, 815 },
    { 2, 817 },
    { 2, 819 },
    { 2, 821 },
    { 2, 823 },
    { 2, 825 },
    { 2, 827 },
    { 2, 829 },
    { 2, 831 },
    { 2, 833 },
    { 2, 835 },
    { 2, 837 },
    { 2, 839 },
    { 2, 841 },
    { 2, 843 },
    { 2, 845 },
    { 2, 847 },
    { 2, 849 },
    { 2, 851 },
    { 2, 853 },
    { 2, 855 },
    { 2, 857 },
    { 2, 859 },
    { 2, 861 },
    { 2, 863 },
    { 2, 865 },
    { 2, 867 },
    { 2, 869 },
    { 0, 0 },
    { 2, 871 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 2, 873 },
    { 2, 875 },
    { 2, 877 },
    { 2, 879 },
    { 3, 881 },
    { 3, 884 },
    { 3, 887 },
    { 3, 890 },
    { 3, 893 },
    { 3, 896 },
    { 3, 899 },
    { 3, 902 },
    { 3, 905 },
    { 3, 908 },
    { 3, 911 },
    { 3, 914 },
    { 3, 917 },
    { 3, 920 },
    { 3, 923 },
    { 3, 926 },
    { 3, 929 },
    { 3, 932 },
    { 3, 935 },
    { 3, 938 },
    { 2, 941 },
    { 2, 943 },
    { 2, 945 },
    { 2, 947 },
    { 2, 949 },
    { 2, 951 },
    { 3, 953 },
    { 3, 956 },
    { 3, 959 },
    { 3, 962 },
    { 3, 965 },
    { 3, 968 },
    { 3, 971 },
    { 3, 974 },
    { 3, 977 },
    { 3, 980 },
    { 2, 983 },
    { 2, 985 },
    { 2, 987 },
    { 2, 989 },
    { 2, 991 },
    { 2, 993 },
    { 2, 995 },
    { 2, 997 },
    { 3, 999 },
    { 3, 1002 },
    { 3, 1005 },
    { 3, 1008 },
    { 3, 1011 },
    { 3, 1014 },
    { 3, 1017 },
    { 3, 1020 },
    { 3, 1023 },
    { 3, 1026 },
    { 3, 1029 },
    { 3, 1032 },
    { 3, 1035 },
    { 3, 1038 },
    { 3, 1041 },
    { 3, 1044 },
    { 3, 1047 },
    { 3, 1050 },
    { 3, 1053 },
    { 3, 1056 },
    { 2, 1059 },
    { 2, 1061 },
    { 2, 1063 },
    { 2, 1065 },
    { 3, 1067 },
    { 3, 1070 },
    { 3, 1073 },
    { 3, 1076 },
    { 3, 1079 },
    { 3, 1082 },
    { 3, 1085 },
    { 3, 1088 },
    { 3, 1091 },
    { 3, 1094 },
    { 2, 1097 },
    { 2, 1099 },
    { 2, 1101 },
    { 2, 1103 },
    { 2, 1105 },
    { 2, 1107 },
    { 2, 1109 },
    { 2, 1111 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
    { 0, 0 },
};

#define GET_DECOMP_BLOCK(ch, blockptr)  \
switch ((glui32)(ch) >> 8) {  \
    case 0x0:  \
        *blockptr = unigen_decomp_block_0x0;  \
        break;  \
    case 0x1:  \
        *blockptr = unigen_decomp_block_0x1;  \
        break;  \
    case 0x2:  \
        *blockptr = unigen_decomp_block_0x2;  \
        break;  \
    case 0x1e:  \
        *blockptr = unigen_decomp_block_0x1e;  \
        break;  \
    default:  \
        *blockptr = NULL;  \
}

#define GET_DECOMP_SPECIAL(ch, countptr, posptr)  \
switch (ch) {  \
    case 0x340:  \
        *countptr = 1; *posptr = 526;  \
        break;  \
    case 0x341:  \
        *countptr = 1; *posptr = 527;  \
        break;  \
    case 0x343:  \
        *countptr = 1; *posptr = 528;  \
        break;  \
    case 0x344:  \
        *countptr = 2; *posptr = 529;  \
        break;  \
    default:  \
        *countptr = 0;  \
}

